### ISSUE TITLE
Image not displaying properly.

### ISSUE THREAD

**Issue by KaasKop97** [dylanaraps/neofetch#257] opened 2016-05-19 17:42 UTC
## Description
Image doesn't display properly, it sort of loads but there are bars just left out.

## System Information
Terminal: rxvt-unicode
Shell: zsh
#### Neofetch version
1.7 / also tried neofetch-git from AUR.
#### Operating system
Arch x64
## Screenshot
http://i.imgur.com/orfbBsh.png
## Verbose log
http://pastebin.com/jF5XqvCa

**Comment by iandrewt** [comment] 2016-05-19 20:20
Image not working in rxvt-unicode is a known issue, see #222

**Comment by KaasKop97** [comment] 2016-05-19 20:34
Wops didn't find that one, sorry!

**Comment by dylanaraps** [comment] 2016-05-20 00:02
Duplicate of #222.

Also see this wiki page:

https://github.com/dylanaraps/neofetch/wiki/Images-in-the-terminal

**Closed by dylanaraps** 2016-05-20 00:02 UTC

**Comment by dylanaraps** [comment] 2016-10-12 21:56
This issue has finally been fixed.
