### ISSUE TITLE
How to  change image in neofetch?

### ISSUE THREAD

**Issue by noptx** [dylanaraps/neofetch#223] opened 2016-04-11 00:14 UTC
I will change the image in Neofetch,whether in this line for change image?
Image Source
--image wall, ascii,path/to/image, /path/to/dir, off
image="wall"

**Comment by dylanaraps** [comment] 2016-04-11 01:05
I don't really understand but here's the example usage for each option:

```sh
# Inside config
# Config is stored in ~/.config/neofetch
image="wall"
image="ascii"
image="/home/dyl/Pictures/image.png"
image="/home/dyl/Pictures/"
image="off"

# At launch
neofetch --image wall
neofetch --image ascii
neofetch --image /home/dyl/Pictures/image.png
neofetch --image /home/dyl/Pictures/

```

**Comment by noptx** [comment] 2016-04-11 13:56
i had try neofetch --image ~/Pictures/image.jpg in terminal and edit in
~/.xinitrc but nothing happen.

**Comment by CousinMachu** [comment] 2016-04-11 18:04
Not sure if this will fix your problem, but do you have any of the dependencies for displaying images (I think they are w3m and imagemagick)? If not, try giving the full path to the image (ex. /home/user/pictures/pic.jpg).

**Comment by noptx** [comment] 2016-04-12 04:20
i use w3m in my Archinux.

On Tue, Apr 12, 2016 at 1:04 AM, Matthew Treadwell <notifications@github.com

**Comment by dylanaraps** [comment] 2016-04-12 06:38
You need both w3m, Imagemagick and a terminal emulator that works with w3m-img installed to use image mode.

What terminal emulator are you using?

**Comment by noptx** [comment] 2016-04-12 07:40
i use rxvt-unicode and xterm.

**Comment by dylanaraps** [comment] 2016-04-12 08:07
Add `set -x` to the 2nd line of the script, it should look like this:

```sh
#!/usr/bin/env bash
set -x
# vim:bla:bla
# ...
# ...
```

Rerun the script and upload the output to pastebin or github gist.

This will tell me exactly what's wrong.

**Comment by noptx** [comment] 2016-04-12 09:35
so,i only add set -x in ~/xinitrc?

**Comment by noptx** [comment] 2016-04-12 09:41
oops,i'm sorry what i mean is config neofetch.

**Comment by dylanaraps** [comment] 2016-04-12 09:46
You add `set -x` to the neofetch executable.

**Comment by noptx** [comment] 2016-04-12 10:07
i just try to add set +x in line 2 config neofetch,but not showing the
image.

**Comment by dylanaraps** [comment] 2016-04-12 10:16
Adding `set -x` to the script just prints a verbose log, it's not supposed to display the script correctly.

**Comment by noptx** [comment] 2016-04-12 10:29
so,what i must do?

**Comment by dylanaraps** [comment] 2016-04-12 10:34
1. Add `set -x` to line 2. (You've already done this)
2. Run `neofetch 2> neofetchlog`
1. Upload the contents of `neofetchlog` to pastebin, gist or equivalent.

**Comment by noptx** [comment] 2016-04-12 10:43
http://pastebin.com/LkLbuArY

**Comment by dylanaraps** [comment] 2016-04-12 10:49
You haven't added `set -x` to line 2 properly so the log file is empty.

**Comment by noptx** [comment] 2016-04-12 11:57
i'm sorry,i check the config evidently i add +x not -x.This is correct log
http://pastebin.com/jE8jm8Tn.

**Comment by dylanaraps** [comment] 2016-04-12 12:38
The script fails to get your terminal size properly, what does this command output?

```sh
printf %b%s '\033[14t'
```

Also, do you currently have X running?

**Comment by noptx** [comment] 2016-04-12 12:41
Nothing happen in terminal.

**Comment by dylanaraps** [comment] 2016-04-12 12:54
This is why the script is falling back to ascii mode and not displaying the image. On my system the command above prints the terminal window size in pixels.

When the command above fails inside the script neofetch disables image mode as the command above is how we calculate padding/dynamic image sizing.

I'm not sure about *why* the escape sequence above isn't working for you, the log above shows that you have all of the dependencies installed and you are using a compatible terminal emulator so in theory it should work just fine...

We now know what the problem is so I'll do my best to resolve this for you, thanks for being so patient thus far.

**Comment by noptx** [comment] 2016-04-12 12:56
Ok,thanks for help me too.

**Comment by dylanaraps** [comment] 2016-04-12 13:02
What is your current shell?

You can find out by using `echo "$SHELL"`.

**Comment by noptx** [comment] 2016-04-12 13:03
I use bash.

**Comment by dylanaraps** [comment] 2016-04-12 13:05
Does this command print anything?

```sh
bash -c "printf %b%s '\033[14t\033[c'"
```

**Comment by noptx** [comment] 2016-04-13 13:23
the command print ^[[?1;2c~  1;2c

**Comment by dylanaraps** [comment] 2016-04-13 13:36
Yeah, that's not an output that neofetch can use. I'm not sure why this isn't working for you but there's really nothing I can do about this. It's an issue with your system/terminal emulator.

You could try other terminal emulators like xfce4-terminal and termite, they work well with the image modes.

I'm going to close this as this isn't a neofetch issue.

For those of you stumbling across this in the future, this issue is about the terminal emulator not supporting/printing the escape sequence for terminal size correctly.

**Closed by dylanaraps** 2016-04-13 13:36 UTC
Labels: Question

**Comment by noptx** [comment] 2016-04-13 13:45
yes,it's right just now i try in xterm and the image display.But in rxvt not display the image.

**Comment by duaneking** [comment] 2020-11-21 20:44
Was WSL involved in this? Was this a Linux host or a win10 wsl host?
