### ISSUE TITLE
LC_ALL: cannot change locale (en_US.UTF-8)

### ISSUE THREAD

**Issue by rudylorren** [dylanaraps/neofetch#204] opened 2016-03-30 16:31 UTC
usr/bin/neofetch: line 1882: warning: snick@lvxixLC_ALL: cannot change locale (en_US.UTF-8)
                   -`                   ----------
                  .o+`                  OS: Arch Linux x86_64
                 `ooo/                  Kernel: 4.4.5-1-ARCH
                `+oooo:                 Uptime: up 1 hour, 21 minutes
               `+oooooo:                Packages: 1086

**Comment by dylanaraps** [comment] 2016-03-30 21:42
Hi, I'll need some more info:

- Neofetch version
- `echo "$LC_ALL"`
- `locale`

**Comment by rudylorren** [comment] 2016-03-30 22:35
aur/neofetch 1.5-1 [installed] (9) (6.96)

nick@lvxix ~ $ echo "$LC_ALL"

nick@lvxix ~ $ locale
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

strange stuff

**Comment by dylanaraps** [comment] 2016-03-30 23:06
I know what the issue is now, I'll fix it when I get home. :+1:

**Comment by dylanaraps** [comment] 2016-03-31 06:36
The issue should be fixed now! :)

**Closed** 2016-03-31 06:36 UTC
Labels: Bug

**Comment by rudylorren** [comment] 2016-03-31 15:13
sweet

**Comment by rudylorren** [comment] 2016-03-31 21:52
So i'm a retard,  I had forgotten to uncomment the locale in locale.conf


sorry for the extra work

**Comment by dylanaraps** [comment] 2016-03-31 22:51
All good, Neofetch should work around incorrect locale settings anyway. :)

**Comment by raphaunix** [comment] 2017-08-28 00:39
This worked for me:

```
echo "LC_ALL="en_GB.utf8"" >> /etc/environment
echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
echo "LANG=en_US.UTF-8" > /etc/locale.conf
locale-gen en_US.UTF-8
```
Enjoy.
