### ISSUE TITLE
[Feature Request] Formatting

### ISSUE THREAD

**Issue by twodotcs** [dylanaraps/neofetch#1241] opened 2019-04-29 19:02 UTC
## Description
Formatting with identical spacing between the title and the info, like `lscpu`.
Example from `lscpu`:
```
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
Address sizes:       43 bits physical, 48 bits virtual
CPU(s):              12
```
I achieved this in Python with this over complicated function:
```
  neofetch = "neofetch grabbed by subprocess or the such would go here"
  neolist1 = neofetch.split('\n')
  neolist1 = ([i.split(':', 1)[0] for i in neolist1])
  width = 20
  iterator = 2
  neolist2 = neofetch.split('\n')[1:-2]
  neolist2 = ([i.split(':', 1)[1] for i in neolist2])
  print(neolist1[0]  + '\n' +  neolist1[1]) ##first 2 lines
  while(iterator<len(neolist2)-2):
        line = neolist1[iterator] + ':'.ljust(width - len(neolist1[iterator])) + neolist2[iterator]
        print(line)
        iterator+=1
```

This is the only workaround I have currently (probably due to my awful coding skills), it would be ideal to have this built into neofetch.

**Comment by konimex** [comment] 2019-05-03 03:02
The `info` system we currently have cannot accommodate, I think. But you can set it manually.

e.g.

```sh
print_info() {
    info "Shell     " shell
    info "Resolution" resolution
    info "DE        " de
    info "WM        " wm
    info "WM Theme  " wm_theme
}
```

and it'll show up properly.

**Comment by dylanaraps** [comment] 2019-05-03 05:58
I may be able to add alignment to the current info system. Will look into it.

**Comment by dylanaraps** [comment] 2020-01-23 09:25
Duplicate of: https://github.com/dylanaraps/neofetch/issues/895

**Closed by dylanaraps** 2020-01-23 09:25 UTC
Labels: Enhancement
