### ISSUE TITLE
ERROR neofetch: line 8680: /dev/stdin: No such file or directory

### ISSUE THREAD

**Issue by fajarekapr** [dylanaraps/neofetch#995] opened 2018-05-19 08:40 UTC
<h3>Can anyone help me for this problem? pls..</h3>
<pre>
neofetch
/data/data/com.termux/files/usr/bin/neofetch: line 8680: /dev/stdin: No such file or directory
         -o          o-            u0_a162@localhost
          +hydNNNNdyh+             -----------------
        +mMMMMMMMMMMMMm+           OS: Android 5.1.1 armv7l
      `dMMm:NMMMMMMN:mMMd`         Host: Anonymous XD :p
      hMMMMMMMMMMMMMMMMMMh         Kernel: 3.10.65-7296443
/data/data/com.termux/files/usr/bin/neofetch: line 8680: printf: wre
.mMMm`MMMMMMMMMMMMMMMMMMMM`mMMm.   Uptime: 1 hour, 8 mins
:MMMM-MMMMMMMMMMMMMMMMMMMM-MMMM:   Packages: 125
:MMMM-MMMMMMMMMMMMMMMMMMMM-MMMM:   Shell: login zsh 5.5.1
:MMMM-MMMMMMMMMMMMMMMMMMMM-MMMM:   Terminal: com.termux
:MMMM-MMMMMMMMMMMMMMMMMMMM-MMMM:   CPU: sc8830 (4) @ 1.500GHz
-MMMM-MMMMMMMMMMMMMMMMMMMM-MMMM-   Memory: 694MiB / 919MiB
 +yy+ MMMMMMMMMMMMMMMMMMMM +yy+
      mMMMMMMMMMMMMMMMMMMm
      `/++MMMMh++hMMMM++/`
          MMMMo  oMMMM
          MMMMo  oMMMM
          oNMm-  -mMNs
</pre>
> Help me pls

**Comment by dylanaraps** [comment] 2018-05-19 10:38
The issue has been fixed in master. Can you download the latest script and tell me if it works?

**Comment by hsiktas** [comment] 2018-05-19 16:46
The issue is gone for me. 👍

![2018-05-19 18 44 58](https://user-images.githubusercontent.com/4571159/40270855-da9f2dce-5b94-11e8-8c60-8f0bcf5389c0.jpg)

**Comment by fajarekapr** [comment] 2018-05-19 16:59
yeah it works

**Closed** 2018-05-19 21:52 UTC
