### ISSUE TITLE
 something wrong on macOS big sur

### ISSUE THREAD

**Issue by kangjiayin** [dylanaraps/neofetch#1674] opened 2021-01-30 05:04 UTC
## Description
Output 'Memory' doesn't right.
#### Neofetch version
7.1.0
## Verbose log

1. Run `neofetch -vv 2> neofetchlog`
2. Upload the contents of `neofetchlog` to pastebin, gist or equivalent.

[neofetchlog.txt](https://github.com/dylanaraps/neofetch/files/5897402/neofetchlog.txt)
<img width="960" alt="Snipaste_2021-01-30_13-02-19" src="https://user-images.githubusercontent.com/67104974/106347719-b0f39980-62fb-11eb-99aa-e5ad3981fc47.png">

**Comment by kattjevfel** [comment] 2021-02-13 13:42
Duplicate of #1663

**Closed** 2021-06-11 06:26 UTC
