### ISSUE TITLE
LC_ALL: cannot change locale (en_US): No such file or directory

### ISSUE THREAD

**Issue by joshbenham** [dylanaraps/neofetch#152] opened 2016-03-16 23:19 UTC
I installed this on the OLD elementary and when I try and run it I get this error and not too sure how I can fix it.

/usr/bin/neofetch: line 1703: warning: josh@echo: LC_ALL: cannot change locale (en_US): No such file or directory

OS: elementary OS Luna x86_64
Kernel: 3.2.0-60-generic
Packages: 2212
Shell: /bin/bash
Resolution: 3520x1080
Desktop Environment: Pantheon
Window Manager: Mutter(Gala)
Theme: Numix [GTK3] 
Icons: Numix-Circle [GTK3] 
CPU: Intel Core i7-3610QM @ 2.3GHz
GPU: Nvidia GeForce GT 650M

**Comment by dylanaraps** [comment] 2016-03-17 01:21
Hello,

- What is your locale set to?
- What version of neofetch are you using?
- Is this a new issue?
- Does this occure on older versions?

**Comment by joshbenham** [comment] 2016-03-17 01:28
Sorry. A pretty crappy ticket left for you.

**What is your locale set to?**
```
$ locale
LANG=en_US
LANGUAGE=en_AU:en
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
```

**What version of neofetch are you using?**
I think I am using **1.5**


**Is this a new issue?**
This is the first time I have ever used it.


**Does this occure on older versions?**
This is the first time I have ever used it.


I am running quite an old version of ElementaryOS. Not sure if that could be the problem.

**Comment by dylanaraps** [comment] 2016-03-17 01:29
I've actually decided to close this as I just had a look and that Elementary OS version is 3 years old now and no longer supported.

**Comment by dylanaraps** [comment] 2016-03-17 01:30
I 've actually just pinpointed the bug, your locale is incorrectly set.

It should be `LANG=en_US.UTF-8` **not** `LANG=en_US`.

**Closed** 2016-03-17 01:30 UTC
Labels: Wontfix

**Comment by joshbenham** [comment] 2016-03-17 01:43
Ok I have seemed to have fixed that error from showing. No idea why that is the case.

It seems that after GPU it stops and does not show things like memory even when I have edited /usr/bin/neofetch as well.

printinfo () {
    info title
    info underline

    info "OS" distro
    info "Kernel" kernel
    info "Uptime" uptime
    info "Packages" packages
    info "Shell" shell
    info "Resolution" resolution
    info "Desktop Environment" de
    info "Window Manager" wm
    info "Theme" theme
    info "Icons" icons
    info "CPU" cpu
    info "GPU" gpu
    info "Memory" memory

    info "Font" font
    info "Disk" disk
    info "Battery" battery
    # info "Local IP" localip
    # info "Public IP" publicip
    info "Users" users
    info "Birthday" birthday
    info "Song" song

    info linebreak
    info cols
    info linebreak
    info linebreak
}

**Comment by dylanaraps** [comment] 2016-03-17 02:25
What happens if you disable the GPU from printing? (Add a # before the line)

**Comment by joshbenham** [comment] 2016-03-17 03:31
It is a bug with printing the memory.
I have enabled everything except memory and they all print. 
I enable memory and it stops before it.

**Comment by dylanaraps** [comment] 2016-03-17 03:47
Working on a fix as we speak.

**Comment by dylanaraps** [comment] 2016-03-17 03:58
Fixed, once you can confirm that it's working I'll close the issue.

**Comment by joshbenham** [comment] 2016-03-17 04:51
This is getting further.

It now does not stall but it measures both sides of memory as the same.

![Neofetch](http://i.imgur.com/Gwg2iB6.png?1)

**Comment by dylanaraps** [comment] 2016-03-17 04:53
What's the out of `cat /proc/meminfo`?

**Comment by joshbenham** [comment] 2016-03-17 05:38
$ cat /proc/meminfo
MemTotal:        8071732 kB
MemFree:          179092 kB
Buffers:          222260 kB
Cached:          1941128 kB
SwapCached:         2660 kB
Active:          5643816 kB
Inactive:        1688240 kB
Active(anon):    4884632 kB
Inactive(anon):   955784 kB
Active(file):     759184 kB
Inactive(file):   732456 kB
Unevictable:          60 kB
Mlocked:              60 kB
SwapTotal:       8282108 kB
SwapFree:        8247172 kB
Dirty:             10904 kB
Writeback:             0 kB
AnonPages:       5166500 kB
Mapped:           694144 kB
Shmem:            671748 kB
Slab:             313748 kB
SReclaimable:     256700 kB
SUnreclaim:        57048 kB
KernelStack:        9216 kB
PageTables:        88208 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:    12317972 kB
Committed_AS:   16323324 kB
VmallocTotal:   34359738367 kB
VmallocUsed:      369932 kB
VmallocChunk:   34359316248 kB
HardwareCorrupted:     0 kB
AnonHugePages:         0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:       90112 kB
DirectMap2M:     8206336 kB

**Comment by dylanaraps** [comment] 2016-03-17 05:44
The issue is that you're missing the `MemAvailable` line from `/proc/meminfo` and I'm pretty sure it's because your kernel version is too low. `MemAvailable` was added early 2014 and you can see the commit here: 

https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=34e431b0ae398fc54ea69ff85ec700722c9da773

I'm sorry but I won't add support for systems that don't have `MemAvailable`, I'm open to merging PRs that add it though. For now you should just disable the info function from displaying.

**Comment by joshbenham** [comment] 2016-03-17 05:50
That is totally ok :)

Thanks for letting me hassle you. Hopefully some of it was useful.

**Comment by dylanaraps** [comment] 2016-03-17 05:51
What else is broken? (I'll add it to my todo list)

**Comment by joshbenham** [comment] 2016-03-17 05:57
Nothing else. The memory part was it and its because I am on an older version. It still executes which is good :)

You can close this.

**Comment by dylanaraps** [comment] 2016-03-17 05:59
If that's all that's broken then I'll try and add support for it.
