### ISSUE TITLE
image overlaps tmux border

### ISSUE THREAD

**Issue by sphaugh** [dylanaraps/neofetch#787] opened 2017-07-26 17:53 UTC
#### Neofetch version
```
Neofetch 3.2.1-git
```

## Screenshot
![overlap](https://user-images.githubusercontent.com/8660255/28635576-ba720a22-7200-11e7-8498-fd07d677d9aa.png)

## Config file
None

## Verbose log
https://gist.github.com/c19c780e30e2761fb181273b11eb15ce

**Comment by dylanaraps** [comment] 2017-07-26 23:51
Duplicate of #768

There's nothing we can do to fix this. 

My reply in #768:
> w3m-img draws on-top of the window, it doesn't know where the terminal cells start/end. It just finds the window it was started from and displays an image on-top of it.

> The workaround is to use the --yoffset 000 flag to set the image offset. Example: neofetch --w3m --yoffset 30.

**Closed by dylanaraps** 2017-07-26 23:51 UTC
