### ISSUE TITLE
Neofetch reports incorrect information on Windows 11 WSL2

### ISSUE THREAD

**Issue by isXander** [dylanaraps/neofetch#1980] opened 2021-12-05 15:03 UTC
## Description
Neofetch reports incorrect information on Windows 11 WSL2 Ubuntu
* OS: wrong windows version
* Terminal: reports device rather than friendly name: Windows Terminal
* GPU: reports microsoft device rather than actual name: (Iris Xe Graphics)

- [x] Does this issue still occur in the master branch? (**Required if issue**)

#### Neofetch version
7.0.0-1

## Screenshot
![](https://cdn.discordapp.com/attachments/888449233110335518/917065493318348910/unknown.png)

## Config file
[default](https://hst.sh/olagoberuc.shell)

## Verbose log
[here](https://hst.sh/ejuloxibop.shell)

**Comment by BobIsMyManager** [comment] 2021-12-05 15:09
Duplicate of #1848

**Comment by isXander** [comment] 2021-12-05 15:11
> Duplicate of #1848

also contains other information such as terminal and gpu

**Closed** 2021-12-06 03:25 UTC

**Comment by nowhereman1999** [comment] 2023-01-07 14:34
> also contains other information such as terminal and gpu

Hi,I also got the same problem with you on win10 22H2:
![image](https://user-images.githubusercontent.com/53631206/211155665-5afce771-a109-4677-80d8-6e0e58a23f39.png)
and here is the output of necfetch -v:
![image](https://user-images.githubusercontent.com/53631206/211155917-7bf5681b-6f33-4a76-9acd-822531f9b4ac.png)
so have you solved it now and could you please give me some advice?
