### ISSUE TITLE
Bold option is not working

### ISSUE THREAD

**Issue by hashhar** [dylanaraps/neofetch#243] opened 2016-05-13 18:03 UTC
## Description
The bold option has no effect through the command line or the config file.

## System Information
rxvt-unicode 9.21
GNOME Terminal 3.16.2

#### Neofetch version
1.7 from git master

#### Operating system
Ubuntu GNOME 15.10

## Screenshot
![2016-05-13_23-30-26_1366x768](https://cloud.githubusercontent.com/assets/10473142/15257178/ba3740ba-1962-11e6-9637-98d399b57d1e.png)

## Verbose log
[Here](https://gist.github.com/hashhar/94b27a5916840ea454db7098d3beb65e)

**Comment by hashhar** [comment] 2016-05-13 18:05
### Things I've Tried:

- Changing terminal emulator.
- Changing font.

**Comment by iandrewt** [comment] 2016-05-13 23:51
Not working in GNOME Terminal 3.20.2 for me either, but the escape sequence works fine (`\033[1mTest` printed **`Test`**)

**Comment by dylanaraps** [comment] 2016-05-14 00:46
I can reproduce this, I'm working on a fix now.

**Comment by dylanaraps** [comment] 2016-05-14 00:57
Fixed in [26b5db8](https://github.com/dylanaraps/neofetch/commit/26b5db822a5bb0a1e60d6d694c6dd3ea5d1cd2de).

This was caused by the changes to the color escape sequences a while back. The color escape sequences clear any formatting before them meaning that the bold escape sequence **was** set and then immediately cleared. 

The solution was to simply set the bold escape sequence **after** the color escape sequences.

Thanks for reporting this issue.

**Closed by dylanaraps** 2016-05-14 00:57 UTC
Labels: Bug

**Comment by iandrewt** [comment] 2016-05-14 01:10
While 26b5db8 fixed the bold issue, the text now has no colour when bold is used

**Comment by dylanaraps** [comment] 2016-05-14 02:00
Which colorscheme are you using? 

If you're using Solarized then this is an issue with Solarized and the way the bold 
escape sequence works. 

The bold escape sequence works by using the bright version of the current text
color. If the text color is `4` (blue) and you set the text to bold the terminal will
use color `12` (brightblue).

Solarized sets all of the bright variants of the colors to different shades of gray,
this makes the bold output look like it's grayscale.

This isn't a neofetch issue and I don't think there's anyway for us to workaround
this issue.

**Comment by iandrewt** [comment] 2016-05-14 04:36
Yeah I am using solarized. I'm probably gonna change it soon anyway, its starting to get a little bright for my taste

**Comment by dylanaraps** [comment] 2016-05-14 04:45
Try out my colorscheme, I made a repo for it a while ago. :)

https://github.com/dylanaraps/ryuuko

**Comment by hashhar** [comment] 2016-05-14 11:26
I'm on the default dark theme though. I'll try writing a patch.

**Comment by hashhar** [comment] 2016-05-14 13:10
My bad. I see you updated it. Wasn't it the missing semicolon though?

**Comment by dylanaraps** [comment] 2016-05-14 13:16
No problem. :)
