### ISSUE TITLE
Problem with SONG + Audacious

### ISSUE THREAD

**Issue by IAmNotImportant** [dylanaraps/neofetch#638] opened 2017-01-25 21:51 UTC
## Description
So, I saw that Debian (Jessie, 8.7) just got new version. Without long talk, **Song** option does not work.
If the `song_shorthand` is off, as is default, the line does not show up at all.
If it is on, the `Song` is displayed, bold, but without heading color (screenshot attached).

```
> audtool current-song
Drunk With Pain - Hail The Monsters - Buried Mind
> audacious --version
Audacious 3.5 (Debian package)
```

#### Neofetch version
```
> neofetch --version
Neofetch 3.0
(...)
```

## Screenshot
![Screenshot with song_shorthand off](https://cloud.githubusercontent.com/assets/14353790/22310363/515f8518-e34f-11e6-84ce-ad79063b78b5.png)

## Verbose log
[http://pastebin.com/1zrsiTVY](http://pastebin.com/1zrsiTVY)

**Comment by ncmprhnsbl** [comment] 2017-01-26 00:57
no problems here with audacious-3.8.2 in void/neofetch-3.0...
though, i don't think it would be an audacious version issue since the output of audtool is the same..

**Comment by dylanaraps** [comment] 2017-01-26 05:40
Can you send me your config file? 

I can't reproduce this either.

Using `audacious 3.8.1` in Arch.

**Comment by mstraube** [comment] 2017-01-26 07:42
I can reproduce it in a tty (on fresh installed debian jessie in VirtualBox).
```
$ audtool current-song
D-Bus error: Cannot aotulaunch D-Bus without X11 $DISPLAY
```
In a terminal emulator under X it works.

The bold `Song` is a general issue with --song_shorthand. It happens if `$song` is empty and `song_shorthand` is on. Can be fixed with 91c85114a44adb9bf16ebe889828cfbee55fa9cb

So the problem seems `audtool current-song` does not return anything.


P.S.
I think it's not the reason for this, but noticed that `audtool current-song` returns `Artist - Album - Title`. Since audtool seems to use dbus anyway I also changed the query for audacious to use `get_song_dbus` in my song branch.

**Comment by dylanaraps** [comment] 2017-01-26 07:49
Sounds good @mstraube!

This seems like a better way of fixing the first issue:

```sh
if [[ "$song_shorthand" == "on" && "$song" ]]; then
```

**Comment by mstraube** [comment] 2017-01-26 08:18
But seems a bit weired that running `audtool current-song` doesn' print the info only from within neofetch.

@IAmNotImportant are you running neofetch from the same terminal in which audtool works for you?

**Comment by dylanaraps** [comment] 2017-01-26 09:12
@mstraube's fixes were pushed to master. Can you try out the latest master and let me know if the issues still persist?

**Comment by IAmNotImportant** [comment] 2017-01-26 19:45
@dylanaraps It works now.

Thanks for it, and whole neofetch too!

**Comment by dylanaraps** [comment] 2017-01-26 23:15
No problem!

**Closed** 2017-01-26 23:15 UTC
Labels: Bug

**Comment by ncmprhnsbl** [comment] 2017-02-14 02:20
audacious song info not working for me now(3.0.1)

``
dbus-send --print-reply --dest=org.mpris.MediaPlayer2.audacious /org/mpris/MediaPlayer2             org.freedesktop.DBus.Properties.Get string:'org.mpris.MediaPlayer2.Player' string:'Metadata' |            awk -F 'string "' '/string|array/ {printf "%s",$2; next}{print ""}' |            awk -F '"' '/artist/ {a=$2} /title/ {t=$2} END{print a " - " t}'
Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.mpris.MediaPlayer2.audacious was not provided by any .service files
``

guessing this would be a problem for any of the dbus_get_song players..
possibly a deficiency of my setup  here on void with openbox..
any idea what package should provide the missing .service(s)?

**Comment by dylanaraps** [comment] 2017-02-14 02:24
I've got no clue.

Does `audtool current-song` work?

**Comment by ncmprhnsbl** [comment] 2017-02-14 02:31
yep

**Comment by ncmprhnsbl** [comment] 2017-02-14 03:26
here: https://wiki.archlinux.org/index.php/Spotify#D-Bus
suggests "setting the dbus address" and provides a script...
which fails (in void) ..presumably because /proc/$PID/eviron is readonly..
might need to take this to void forum becuase i notice it effects `playerctl` too..

**Comment by dylanaraps** [comment] 2017-02-16 23:23
Weird. 

I thought `audtool` used dbus since @mstraube got this error on his machine:

```sh
$ audtool current-song
D-Bus error: Cannot autolaunch D-Bus without X11 $DISPLAY
```

I've pushed a fix to master that uses `audtool` and if `audtool` fails it fallsback to `dbus-send`. 

Sorry for the delay.

**Comment by mstraube** [comment] 2017-02-17 11:01
> I've pushed a fix to master that uses audtool and if audtool fails it fallsback to dbus-send.

In the fix `$song` is not set, `audtool` just prints the info. Shouldn't it be ?
```bash
        "audacious"*)    song="$(audtool current-song)" || get_song_dbus "audacious" ;;
```
Or to make audacious song info more consistent with the others (Artist - Title) maybe something like this? 
```bash
        "audacious"*)
            song="$(audtool current-song)"
            # Remove Album from 'Artist - Album - Title'
            song="${song/-* -/-}"
            [[ -z "$song" ]] && get_song_dbus "audacious"
        ;;
```

**Comment by ncmprhnsbl** [comment] 2017-02-17 22:49
tested and confirming what mstraube says (and fix)...
and agree with second point..
i suspect any weirdness regarding dbus-send could be peculiar to my  void setup.. i've yet to check it out on some other OSs..

**Comment by dylanaraps** [comment] 2017-02-18 23:40
Sorry guys, my "fix" was rushed.

Thanks for the working fix @mstraube
