### ISSUE TITLE
Image not displayed

### ISSUE THREAD

**Issue by oblitum** [dylanaraps/neofetch#745] opened 2017-06-08 20:45 UTC
## Description

Just installed, I'm on ArchLinux using xfce4-terminal and image isn't displayed using `neofetch --w3m`:

```
(1/1) installing neofetch
Optional dependencies for neofetch
    feh: Wallpaper Display
    imagemagick: Image cropping / Thumbnail creation / Take a screenshot [installed]
    nitrogen: Wallpaper Display
    w3m: Display Images [installed]
    catimg: Display Images
    jp2a: Display Images [installed]
    libcaca: Display Images [installed]
    xdotool: See https://github.com/dylanaraps/neofetch/wiki/Images-in-the-terminal [installed]
    xorg-xdpyinfo: Resolution detection (Single Monitor) [installed]
    xorg-xprop: Desktop Environment and Window Manager [installed]
    xorg-xrandr: Resolution detection (Multi Monitor + Refresh rates) [installed]
    xorg-xwininfo: See https://github.com/dylanaraps/neofetch/wiki/Images-in-the-terminal
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
```

#### Neofetch version

Neofetch 3.1.0

## Screenshot

https://i.imgur.com/uXEPXPx.png

## Config file

Default

## Verbose log

https://gist.github.com/oblitum/3f3981f6ba7ef65f417094313c43c4e4#file-gistfile1-txt

**Comment by dylanaraps** [comment] 2017-06-09 00:14
Do images work in `w3m` or `ranger`?

**Comment by oblitum** [comment] 2017-06-09 17:46
In `w3m` which is already installed, no it doesn't work. Notice that I've opened the issue since Wiki tells it works on xfce4-terminal.

**Comment by dylanaraps** [comment] 2017-06-09 23:07
`w3m-img` is extremely finicky and doesn't always work despite the environment being identical to a working one. The log file tells me that Neofetch is functioning correctly, this is a `w3m-img` issue.

There's nothing I can do to fix this.

Duplicate of https://github.com/dylanaraps/neofetch/issues/739, https://github.com/dylanaraps/neofetch/issues/728

**Closed by dylanaraps** 2017-06-09 23:07 UTC
