### ISSUE TITLE
Neofetch can't be piped into Lolcat

### ISSUE THREAD

**Issue by rockrij** [dylanaraps/neofetch#685] opened 2017-03-30 06:29 UTC
Hello again!

Neofetch output is ugly (info is displayed below the logo and has unknown characters) when using Lolcat. On the left side of the picture shows Neofetch outputs on different terminals. On the right side are Screenfetch outputs just to compare.
![screenshot_2017-03-30_14-11-22](https://cloud.githubusercontent.com/assets/26760601/24490328/bc50ba9a-1554-11e7-8ab8-67258e0ab401.png)

Thanks!

**Comment by konimex** [comment] 2017-03-30 06:31
Duplicate of #666, closing this.

**Closed by konimex** 2017-03-30 06:31 UTC

**Comment by dylanaraps** [comment] 2018-06-19 22:56
Neofetch now works with `lolcat`! :fireworks:

**Comment by rockrij** [comment] 2018-06-20 09:27
nice! thanks!
