### ISSUE TITLE
Package Update Thread

### ISSUE THREAD

**Issue by dylanaraps** [dylanaraps/neofetch#115] opened 2016-02-28 10:05 UTC
Those maintaining packages for Neofetch can post updates here.

**Packages:**

[![Packaging status](https://repology.org/badge/vertical-allrepos/neofetch.svg)](https://repology.org/metapackage/neofetch)

**Third-Party Packages:**

| Distro | Type | Maintainer | URL | Latest Release |
| --- | --- | --- | --- | --- |
| Crux | Port | @6c37 | [neofetch-git](https://github.com/6c37/crux-ports-git) | Yes (Git) |
| Debian | Repo | @dawidd6 | https://bintray.com/dawidd6/neofetch/neofetch  | Yes |
| Fedora | COPR | @konimex | (see RHEL/CentOS) | Yes |
| Mageia | COPR | @konimex | (see RHEL/CentOS) | Yes |
| RHEL/CentOS | COPR | @konimex | http://copr.fedorainfracloud.org/coprs/konimex/neofetch/  | Yes |
| Ubuntu | PPA | @dawidd6 | https://launchpad.net/~dawidd0811/+archive/ubuntu/neofetch/  |  |
| Ubuntu Daily | PPA | @dawidd6  | https://launchpad.net/~dawidd0811/+archive/ubuntu/neofetch-daily | Yes (Git) |

**Coming Soon, Official Packages:**

| Distro | Type | URL |
| --- | --- | --- |

**Comment by dawidd6** [comment] 2016-02-28 10:52
I've updated .deb package to 1.4-2, because of missing optional dependencies and required procps. Now package is fully armed :+1:

**Comment by ix** [comment] 2016-03-03 23:59
i've moved most of my projects to a personal git server at http://arcetera.moe/git

please change https://git.io/vgNJ6 to http://arcetera.moe/sync

**Comment by dylanaraps** [comment] 2016-03-04 01:04
Done.

**Comment by dylanaraps** [comment] 2016-03-04 22:25
Neofetch now has a manpage, the manpage is installed by the makefile but I'm
not sure if you guys need to make any modifications on your end for it to work.

The makefile installs the manpage to `/usr/share/man/man1`.

**Comment by ix** [comment] 2016-03-05 01:07
Doubt it; if it's handled by the Makefile it should be fine.

**Comment by ix** [comment] 2016-03-05 01:30
i've now moved from git to httpup to qualify for the crux portdb; i've also set up https so you'll have to change from http://arcetera.moe/sync to https://arcetera.moe/sync

**Comment by dylanaraps** [comment] 2016-03-05 02:19
Done.

**Comment by dylanaraps** [comment] 2016-03-09 12:01
1.4 has been released.

ping @ix, @dawidd6 and @z1lt0id.

**Comment by ix** [comment] 2016-03-09 12:12
my port just fetches straight from git not from a release tarball, so it's fine

**Comment by dylanaraps** [comment] 2016-03-09 12:15
I see, I'll keep that in mind. :)

**Comment by iandrewt** [comment] 2016-03-09 12:35
Homebrew pull request has been submitted, shouldn't take too long to be accepted

**Comment by dylanaraps** [comment] 2016-03-09 12:37
Awesome!

**Comment by dawidd6** [comment] 2016-03-09 15:20
.deb updated :+1:

**Comment by dawidd6** [comment] 2016-03-09 19:08
https://github.com/Linuxbrew/linuxbrew

It's using homebrew's formulaes i think, so i suppose that neofetch will be available here too. Thanks to @iandrewt :)

**Comment by z1lt0id** [comment] 2016-03-09 23:41
Neofetch 1.4 ebuild has been updated

**Comment by dylanaraps** [comment] 2016-03-09 23:46
Thanks guys! :+1:

**Comment by iandrewt** [comment] 2016-03-10 00:16
I'm hoping Homebrew's test servers decide to behave better than my laptop, `brew test neofetch` doesn't exit for me (it just runs the ruby command `system "#{bin}/neofetch`). Does the script return 0 when it exits?

**Comment by dylanaraps** [comment] 2016-03-10 00:22
The script returns `0` when it exits without an error.

**Comment by iandrewt** [comment] 2016-03-10 00:29
Seems to be my MacBook then, [here's the brew test-bot result](http://bot.brew.sh/job/Homebrew%20Pull%20Requests/43012/)
Passed with no issues

**Comment by dylanaraps** [comment] 2016-03-10 00:36
I can't seem to view the result.

![2016-03-10-113447_956x484_scrot](https://cloud.githubusercontent.com/assets/6799467/13655543/461af144-e6b4-11e5-9e9b-9a6e20ccbcc4.png)

**Comment by dylanaraps** [comment] 2016-03-10 00:43
I can view it now, just had to authorize it.

**Comment by dylanaraps** [comment] 2016-03-10 00:45
So what you're saying is that the hombrew formula fails on your MacBook but works on Homebrew's test servers?

**Comment by iandrewt** [comment] 2016-03-10 00:56
Sorta. It installs fine, runs fine, `brew audit --strict --online neofetch` passes and everything, but the test script (which Homebrew requires for submission) fails on my MacBook (never finishes) but works on Homebrew's test servers.

**Comment by iandrewt** [comment] 2016-03-10 01:05
@dawidd6 yep, it'll be in Linuxbrew shortly after it gets accepted by Homebrew, and that'll happen automatically. Another Homebrew package I maintain ([`dropbox-uploader`](https://github.com/andreafabrizi/Dropbox-Uploader)) was put in there without any intervention from me.

**Comment by dylanaraps** [comment] 2016-03-10 01:08
Weird, does neofetch run fine on your system?

**Comment by iandrewt** [comment] 2016-03-10 01:13
Yeah, runs fine, everything works. It's just the test script. If I run `brew test --verbose neofetch` it produces the correct output then just hangs without exiting. Without verbose it won't show output from the program, but that's expected behaviour.

I'll test it on my Hackintosh once I've finished setting that up this afternoon.

**Comment by z1lt0id** [comment] 2016-03-10 01:46
Also just letting you know, that the man page works wonderfully on the ebuild also.

**Comment by dylanaraps** [comment] 2016-03-10 01:46
Awesome :+1:

**Comment by konimex** [comment] 2016-03-11 12:25
Some small update for Fedora and RHEL/CentOS packages.

Fedora's package will have these dependencies:

* xorg-xprop
* ImageMagick
* w3m-img

However, this is not the case in RHEL/CentOS packages because usually
they (usually) won't have Xorg at all.

**Comment by dylanaraps** [comment] 2016-03-11 12:27
Is it possible to make them optional dependencies on RHEL/CentOS?

**Comment by konimex** [comment] 2016-03-11 12:35
On 03/11/2016 07:27 PM, Dylan Araps wrote:
> Is it possible to make them optional dependencies on RHEL/CentOS?

Unfortunately, RPM does not seem to know the concept of optdepends,
unlike AUR. However I can tell the users about the optional dependencies
by using the %post scriptlet, I'll see what I can do.

**Comment by dylanaraps** [comment] 2016-03-11 12:40
If it's too difficult then don't worry about it. :)

**Comment by konimex** [comment] 2016-03-11 13:25
Okay, so I circumvented the lack of optional dependencies by utilizing
the post-install mechanism. Same as before, xorg-x11-utils (which
contains xorg-xprop) will be a required dependency in Fedora, but an
optional dependency in RHEL/CentOS.

**Comment by dylanaraps** [comment] 2016-03-17 05:58
Neofetch 1.5 has been released, just a reminder to update your packages.

**Comment by dawidd6** [comment] 2016-03-17 14:33
updated :ok:

**Comment by konimex** [comment] 2016-03-18 16:09
Updated packages for all Fedora and RHEL/CentOS versions. Also, I'm planning to add another repo for RHEL/CentOS 6.

I also submitted a package to [Void Linux](https://github.com/voidlinux/void-packages/pull/3824) so it can get into the official repository.

**Comment by z1lt0id** [comment] 2016-03-18 19:22
Updated of course :)

**Comment by dylanaraps** [comment] 2016-04-01 10:50
I just released Neofetch 1.6, just a reminder to update your packages.

**Comment by ix** [comment] 2016-04-01 12:03
I can no longer maintain the CRUX port as I have switched to OpenBSD.

**Comment by dylanaraps** [comment] 2016-04-01 12:13
I'll go ahead and remove you from the table at the top, thanks for creating/maintaining the port in the first place!

**Comment by dawidd6** [comment] 2016-04-01 13:56
Done. Neofetch 1.6 available

**Comment by tudurom** [comment] 2016-04-01 14:58
i'll maintain the port, let me finish my crux install

**Comment by dylanaraps** [comment] 2016-04-01 15:23
Awesome :+1:

**Comment by tudurom** [comment] 2016-04-02 20:07
Ok, now I maintain all of ix's ports at https://github.com/tudurom/crux-ports.

**Comment by tudurom** [comment] 2016-04-02 20:09
Coming with install instructions...

**Comment by dylanaraps** [comment] 2016-04-03 00:39
Awesome!

**Comment by ix** [comment] 2016-04-03 02:08
very many thanks to @tudurom

**Comment by dawidd6** [comment] 2016-04-04 17:09
Just a small stat:

Total downloads of neofetch deb packages: **567**

**Comment by ix** [comment] 2016-04-04 18:41
I'll probably make an OpenBSD port once I figure it out. It probably won't be accepted into ports though.

**Comment by dawidd6** [comment] 2016-04-28 19:28
I'm setting up now a PPA for neofetch (finally), so soon i hope it will be available :)

I'll keep updating old bintray mirror too, especially for debian.

**Comment by dylanaraps** [comment] 2016-05-14 11:56
Neofetch 1.7 has been released, just a reminder to update your packages. :)

**Comment by dylanaraps** [comment] 2016-05-14 13:08
**Note:** xprop has been changed to an optional dependency as neofetch will work just fine without it.

**Comment by dawidd6** [comment] 2016-05-14 13:36
Bintray and PPA updated :)

**Comment by dylanaraps** [comment] 2016-05-14 13:38
The aur packages have also been updated. :)

**Comment by konimex** [comment] 2016-05-14 13:44
Updated Fedora, RHEL and Void.

**Comment by konimex** [comment] 2016-05-29 10:05
Since Gentoo's package seems not to be updated, I'll try to submit it to official repos.

**Comment by tudurom** [comment] 2016-06-10 16:18
Since I don't use CRUX anymore, I added the port to [6c37](https://github.com/6c37/crux-ports). Please update the table correspondingly.

**Comment by dylanaraps** [comment] 2016-06-10 23:07
Done :+1:

**Comment by tudurom** [comment] 2016-06-11 10:04
oops, i put it in the wrong repo. it's [here](https://github.com/6c37/crux-ports-git) now.

**Comment by dylanaraps** [comment] 2016-06-11 12:28
Fixed.

**Comment by konimex** [comment] 2016-06-13 12:13
Since @z1lt0id didn't update his overlay (and he's been inactive for a while, also as of now there are no response from the Gentoo team about my submission), I have made another overlay, and if you don't mind, I'll take over and I'll write a new instruction.

**Comment by dylanaraps** [comment] 2016-06-13 12:16
Go ahead!

**Comment by tudurom** [comment] 2016-06-13 14:40
iirc @z1lt0id uses arch now

**Comment by konimex** [comment] 2016-08-01 12:45
Hello, I'd like to announce that [neofetch is now in SlackBuilds](https://slackbuilds.org/cgit/slackbuilds/commit/?id=de46791c8) (aka. Slackware's AUR?) and I'll maintain the script. However, the files won't be available at least until 5 August, after I can confirm that the files are available on the website, I'll update the instructions for Slackware.

**Comment by dylanaraps** [comment] 2016-08-01 12:45
Awesome! Thanks again @konimex.

**Comment by dylanaraps** [comment] 2016-08-12 13:20
Neofetch now has a cydia repo/package, see the instructions in the readme for how to install. :)

**Comment by dylanaraps** [comment] 2016-10-02 03:09
Neofetch 1.8 has been released.

**Comment by iandrewt** [comment] 2016-10-02 03:44
Pull request for the macOS update (Homebrew) has been made

homebrew/homebrew-core#5499

**Comment by konimex** [comment] 2016-10-02 04:48
Updated [Fedora, RHEL, CentOS](http://copr.fedorainfracloud.org/coprs/konimex/neofetch/build/460174/), and Gentoo. Sent PR to [Void](https://github.com/voidlinux/void-packages/pull/4869) and SlackBuilds.

**Comment by Vaelatern** [comment] 2016-10-02 06:34
Void PR merged

**Comment by dylanaraps** [comment] 2016-10-02 06:34
Thanks!

**Comment by dawidd6** [comment] 2016-10-02 18:31
Debian and Ubuntu up-to-date

**Comment by dylanaraps** [comment] 2016-10-04 00:55
Neofetch 1.8.1 has been released.

**Comment by iandrewt** [comment] 2016-10-04 01:20
PR to Homebrew has been submitted. 1.8 was accepted yesterday btw

**Comment by konimex** [comment] 2016-10-04 13:39
[PR sent to Void](https://github.com/voidlinux/void-packages/pull/4883). Request submitted to SlackBuilds. Gentoo and RPM-based distros updated.

**Comment by konimex** [comment] 2016-10-05 14:22
[Slackbuilds PR accepted](https://slackbuilds.org/cgit/slackbuilds/commit/?id=5e8b2d0da), the new slackbuild should be live this Sunday.

**Comment by konimex** [comment] 2016-10-31 12:40
Hello, an Android/Termux package is ready to be rolled out (aka. [will be PR'd to upstream](https://github.com/konimex/termux-packages/commit/1c523de0403daa7e4a0af2e124c5bb24abb9269e)) once 1.9 is released. I have tested one package with 1.8.1 and so far so good (The `#!/usr/bin/env` problem is resolved). Instructions to follow.

**Comment by dylanaraps** [comment] 2016-11-01 06:51
1.9 has been released.

**Comment by konimex** [comment] 2016-11-01 08:10
[PR sent to Termux](https://github.com/termux/termux-packages/pull/531), the rest of packages I maintain will be updated tonight after I get home. Instructions for Termux to follow.

**Comment by dawidd6** [comment] 2016-11-01 10:46
1.9 Done

**Comment by konimex** [comment] 2016-11-01 14:13
PR sent to [Gentoo](https://github.com/gentoo/gentoo/pull/2711), [Void](https://github.com/voidlinux/void-packages/pull/5100), and SlackBuilds. 

Note for Gentoo: There will be no dependencies on `xdpyinfo` since `xprop` and `xrandr` filled the tasks better. Besides, `xprop` is also used for detecting DEs and WMs.

Updates for RPM-based distros will have to be delayed since I can't login into my account at copr (server-side problems).

**Comment by dylanaraps** [comment] 2016-11-01 14:14
:+1:

**Comment by konimex** [comment] 2016-11-02 16:32
[SlackBuild PR accepted](https://slackbuilds.org/cgit/slackbuilds/commit/?id=cdda47a60), should be live next Sunday/Monday (depending on your timezone).

RPM-based distros updated to 1.9.

**Comment by dylanaraps** [comment] 2016-11-04 07:49
Neofetch 1.9.1 has been released.

**Comment by dawidd6** [comment] 2016-11-04 09:22
Done my duty.

Also you can add these URLs to the table:
**Debian**:
sh```https://bintray.com/dawidd6/neofetch/neofetch```
**Ubuntu**:
sh```https://launchpad.net/~dawidd0811/+archive/ubuntu/neofetch/```

**Comment by dylanaraps** [comment] 2016-11-04 09:23
:+1:

**Comment by konimex** [comment] 2016-11-07 14:01
RHEL/CentOS fully updated.
However, Fedora builds for the following version and arch are not yet updated:

- Fedora 23 x86_64
- Fedora 24 x86_64
- Fedora 25 ppc64le
- Fedora Rawhide ppc64le

Because of build errors, and I can't upload new files (again) because of server problems.

I've also added experimental support for Mageia 6 and Mageia cauldron. Keep in mind that this is not yet tested and will not be supported for now.

**Comment by konimex** [comment] 2016-11-08 16:35
Fedora fully updated.

**Comment by konimex** [comment] 2016-11-25 13:16
For the Gentoo link, you can use [this](https://packages.gentoo.org/packages/app-misc/neofetch) one instead of linking to Gentoo's Girhub page.

SlackBuilds PR should be live this Saturday/Sunday.

**Comment by dylanaraps** [comment] 2016-11-25 13:18
Sure thing, thanks! :+1:

**Comment by dylanaraps** [comment] 2016-12-02 09:54
Neofetch 2.0 has been released. :)

**Comment by dawidd6** [comment] 2016-12-02 10:08
As for now i don't have a PC (except rpi), i'm still waiting for delivery, so my packages will not be updated until sunday i think, maybe later.

I don't know if debian and ubuntu maintainers are going to add neofetch for older distros. Do anyone knows anything about that?

**Comment by dylanaraps** [comment] 2016-12-02 10:10
All good.

I'm not sure if neofetch will be released for the older distros, it might be worth asking @iwamatsu. (Maintainer of both packages)

**Comment by konimex** [comment] 2016-12-02 10:34
PR sent to [Termux](https://github.com/termux/termux-packages/pull/574), [Gentoo](https://github.com/gentoo/gentoo/pull/2981), [Void](https://github.com/voidlinux/void-packages/pull/5272), and SlackBuilds. Fedora/RHEL/CentOS should be fully upgraded at this point. Experimental packages for Mageia 6 and cauldron still running.

**Comment by konimex** [comment] 2016-12-03 03:16
irSlackware updated.

I see the table still have Gentoo as third-party, I think you can move it to the official one.

**Comment by dylanaraps** [comment] 2016-12-03 03:17
Fixed, thanks!

**Comment by dawidd6** [comment] 2016-12-03 10:32
My repos are up-to-date now

**Comment by dylanaraps** [comment] 2016-12-06 01:04
Neofetch 2.0.1 has been released.

**Comment by dawidd6** [comment] 2016-12-06 11:00
Updated

**Comment by konimex** [comment] 2016-12-06 11:35
All RPM-based distros updated. PR sent to [Termux](https://github.com/termux/termux-packages/pull/580), [Gentoo](https://github.com/gentoo/gentoo/pull/3030), and [Void](https://github.com/voidlinux/void-packages/pull/5296). Slackware will be delayed until this Friday.

Also, if there are no severe bugs in neofetch-2.0.x, neofetch-2.0.1 will be undergo stabilization (that is, user will be able to install neofetch without modifying their `package.keywords` file) in Gentoo in next month.

**Comment by dylanaraps** [comment] 2016-12-06 11:41
Yup, 2.0.1 is stable. 

Thanks guys!

**Comment by dylanaraps** [comment] 2016-12-06 23:50
**NOTE:** I'm going to be releasing `2.0.2` today. An important bug was found right after `2.0.1` was released and it warrants another release. Here's my explanation from the changelog:

> This minor release fixes some issues related to new features added in 2.0. These issues weren't picked up in the time between 2.0 and 2.1 and another minor release is needed due to the Packages issue being rather important.

> These issues were fixed by reverting the GPU caching and Packages optimizations. These issues occurred because not enough testing was done before these were implemented in master. In the future I'll take more care with testing these larger changes before they hit the master branch and I apologize for there being yet another release in one week.

> I also want to apologize to those packaging Neofetch for this unexpected release.

**Comment by dylanaraps** [comment] 2016-12-07 01:22
Neofetch 2.0.2 has been released.

**Comment by konimex** [comment] 2016-12-07 11:32
[Void updated](https://github.com/voidlinux/void-packages/commit/a112d2ee66ec021410d42a7807c757c97e7f0710), RPM distros updated, [Slackware should be updated by this Saturday](https://slackbuilds.org/cgit/slackbuilds/commit/?id=74fdd314e), and we're still waiting for [Gentoo](https://github.com/gentoo/gentoo/pull/3046).

**Comment by dawidd6** [comment] 2016-12-07 18:45
2.0.2 done

**Comment by iandrewt** [comment] 2016-12-07 22:18
2.0.2 up to date in Homebrew

**Comment by MingcongBai** [comment] 2016-12-13 14:21
2.0.2 is now in [AOSC OS](https://aosc.io/) official repository, build config [here](https://github.com/AOSC-Dev/aosc-os-abbs/tree/staging/extra-utils/neofetch), maintained by @LER0ever.

**Comment by konimex** [comment] 2016-12-13 14:44
Updated, thanks. 👍

**Comment by alibabzo** [comment] 2017-01-22 20:50
Added neofetch to [NixOS package repository](https://github.com/NixOS/nixpkgs/).

**Comment by dylanaraps** [comment] 2017-01-23 05:22
Neofetch 3.0 has been released.

**Comment by LER0ever** [comment] 2017-01-23 06:03
3.0 updated in [AOSC OS](https://github.com/AOSC-Dev/aosc-os-abbs) via commit [1048994](https://github.com/AOSC-Dev/aosc-os-abbs/commit/1048994add578ff73acdaac926dd39d3f72ad268).

**Comment by 2ion** [comment] 2017-01-23 11:35
3.0 updated in BunsenLabs jessie-backports: https://github.com/BunsenLabs/neofetch/commit/370bc6a3409bb2511eb9923100a89f16bb513db8. .debs are available @ https://www.bunsenlabs.org/repoidx.html?k=name-description&v=neofetch.

**Comment by dylanaraps** [comment] 2017-01-23 11:36
Thanks. :+1:

**Comment by MingcongBai** [comment] 2017-01-23 14:01
> 3.0 updated in AOSC OS via commit 1048994.

Was about to send in a reminder, hah. Thanks.

**Comment by alibabzo** [comment] 2017-01-23 23:17
3.0 updated in nixpkgs: https://github.com/NixOS/nixpkgs/commit/231ecebfc60515d317f3a2569d7823b337f210a1

**Comment by dawidd6** [comment] 2017-01-27 18:33
Just wanted to say, that i've set up an additional ppa. Neofetch source is automatically imported from github to launchpad and then packages are being built also automatically using recipe.

https://launchpad.net/~dawidd0811/+archive/ubuntu/neofetch-daily

It's only a curio, but i think neofetch-master is stable enough, which not means i'll stop updating old ppa.

**Comment by dylanaraps** [comment] 2017-01-30 09:12
3.0.1 has been released which fixes all of the bugs found since 3.0's release.

**Comment by alibabzo** [comment] 2017-01-30 20:40
3.0.1 updated https://github.com/NixOS/nixpkgs/commit/df8195b6038136cfd08865be22e3e3c394990031

**Comment by MingcongBai** [comment] 2017-02-01 02:01
AOSC OS's package updated to 3.0.1 via https://github.com/AOSC-Dev/aosc-os-abbs/commit/a06700e2f3df00a824d885f5a72d56ec0b48ce3d.

**Comment by iwamatsu** [comment] 2017-02-02 22:22
3.0 and 3.0.1 up to date in debian/experimental.

**Comment by dylanaraps** [comment] 2017-04-25 03:02
Neofetch 3.1.0 has been released.

**Comment by LER0ever** [comment] 2017-04-25 03:47
Updated to 3.1.0 for AOSC OS via [aosc-os-abbs@784dc0f](https://github.com/AOSC-Dev/aosc-os-abbs/commit/784dc0f5a2d996494c6881d3f84570314d0ba7c0)

**Comment by dawidd6** [comment] 2017-04-25 19:54
3.1.0 updated in Debian && Ubuntu

**Comment by dylanaraps** [comment] 2017-06-21 01:11
Neofetch 3.2.0 has been released.

**Comment by iandrewt** [comment] 2017-06-21 02:00
PR for homebrew created

**Comment by LER0ever** [comment] 2017-06-21 06:07
Package updated for AOSC OS via [9125c17](https://github.com/AOSC-Dev/aosc-os-abbs/commit/9125c175eba2a39bc9fb90ce70da7419cb9e8356)

**Comment by dawidd6** [comment] 2017-06-21 10:41
Done. Also please remove Git from Ubuntu, because it's not true

**Comment by MingcongBai** [comment] 2017-06-25 07:39
Please update AOSC OS's package link to https://packages.aosc.io/packages/neofetch, we have just put a dedicated package information site online... More informative perhaps when compared to a Git tree.

**Comment by dylanaraps** [comment] 2017-06-25 07:42
Done.

**Comment by dawidd6** [comment] 2017-06-25 21:38
Waiting for developers to accept neofetch addition to official Alpine "testing" repository alpinelinux/aports#1761

**Comment by konimex** [comment] 2017-07-01 11:15
To all **git/development package maintainers**: Please update your build package method for the -git version of the package.

**Comment by 2ion** [comment] 2017-07-01 14:01
On Sat, Jul 01, 2017 at 11:15:05AM +0000, Herdiansyah wrote:
> To all **git/development package maintainers**: Please update your build package method for the -git version of the package.

Actually, Debian's dh_auto_install debhelper picks up install.sh
automagically, so boilerplate Debian packaging continues to work
unchanged.

**Comment by dawidd6** [comment] 2017-07-01 14:13
Yes it's building but the package does not contain any files. You need to override dh_auto_install in rules

**Comment by MingcongBai** [comment] 2017-07-01 14:29
Sorry but just another nick-picking... "AOSC" is the name of our community, while "AOSC OS" is the Linux Distribution in which this package is shipped.

**Comment by dylanaraps** [comment] 2017-07-01 14:30
Done.

**Comment by 2ion** [comment] 2017-07-01 15:49
On Sat, Jul 01, 2017 at 07:13:17AM -0700, Dawid Dziurla wrote:
> Yes it's building but the package does not contain any files. You need to override dh_auto_install in rules

Touché.

I had just merged tag 3.2.0 and assumed that due to having been posted
in this thread, that change was already in-tree. Turns that isn't the
case (3.2.0 announcement was already 1 week ago).

In that case, #754 is not a very good fix, since the `$(DESTDIR)$(PREFIX)`
idiom in Makefiles in conjunction with the install target is a fairly
standard way of writing Makefiles (even Suckless projects follow this
practice), being covered by many automated build systems like debhelper.

```make
# $PREFIX, $DESTDIR come from the environment when make is called as
# such: make DESTDIR=$pkgdir PREFIX=/usr install

PREFIX   ?= /usr
PREFIX    = $(DESTDIR)$(PREFIX)
TARGETDIR = $(PREFIX)/bin
DOCSDIR   = $(PREFIX)/share/doc

install: build
  install -Dm755 neofetch $(TARGETDIR)/neofetch
  install -Dm644 README $(TARGETDIR)
```

Well, it's not tragic.

**Comment by dawidd6** [comment] 2017-07-01 15:57
Hey @dylanaraps could you add new entry to the table according to this:

https://github.com/dylanaraps/neofetch/wiki/Installation/84d82512905ba8f61ede42bb0df114910cd589a0#ubuntu-daily-builds

**Comment by dylanaraps** [comment] 2017-07-01 23:59
Done!

**Comment by dawidd6** [comment] 2017-07-10 16:46
Neofetch is now present in Alpine's official "testing" repository

https://github.com/alpinelinux/aports/commit/d81d608f0d56ed02e02d63dd0b32ac1ad99b84e0

**Comment by konimex** [comment] 2017-07-12 07:08
To all **git/developers** package maintainers:

First of all, My apologies because I personally implemented the install script 2 weeks ago and rolled it back, but you are now able to make use of the Makefiles again. Make sure to update your respective build/recipes.

For all packagers with prefixed systems, make sure to set your `SYSCONFDIR` accordingly.

Thanks.

**Comment by konimex** [comment] 2017-07-16 18:49
The third-party COPR (Fedora/RHEL) for Neofetch now supports Mageia 6 and any newer version (cauldron).

**Comment by dylanaraps** [comment] 2017-09-14 00:18
Neofetch `3.3.0` has been released.

**Comment by LER0ever** [comment] 2017-09-14 03:15
Package updated for AOSC OS via [bba4250](https://github.com/AOSC-Dev/aosc-os-abbs/commit/bba425003aa83a310d611e09bdf4e7fe4673c5ff)

**Comment by iandrewt** [comment] 2017-09-14 04:31
Homebrew PR submitted homebrew/homebrew-core#18052

**Comment by konimex** [comment] 2017-09-14 05:37
For all packagers with recipes replacing/substituting Makefile, make sure you have set it accordingly as we have added `SYSCONFDIR` and `MANDIR` as a flag.

**Comment by dawidd6** [comment] 2017-09-14 08:42
Debian - updated
Alpine - https://github.com/alpinelinux/aports/pull/2307
Ubuntu - will be updated, when launchpad build will work

**Comment by AquaL1te** [comment] 2017-12-17 20:05
Neofetch 3.3 just got pushed to Fedora stable: https://bodhi.fedoraproject.org/updates/FEDORA-2017-b9c158f42a

**Comment by dylanaraps** [comment] 2018-04-05 22:46
Neofetch `3.4.0` has been released.

**Comment by MingcongBai** [comment] 2018-04-14 16:39
AOSC OS has been updated to 3.4.0.

**Comment by MingcongBai** [comment] 2018-04-24 03:49
Requesting changing "AOSC" on the chart to "AOSC OS", AOSC is the name of our community (Anthon Open Source Community), while AOSC OS is our distribution project.

**Comment by konimex** [comment] 2018-04-24 03:58
You can ask the [repology](https://repology.org) team for that. We're not responsible for that.

**Comment by dylanaraps** [comment] 2018-05-17 05:09
Neofetch `4.0,0` has been released.

**Comment by dylanaraps** [comment] 2018-06-19 01:35
Neofetch `5.0.0` has been released.

**Comment by dawidd6** [comment] 2018-07-15 11:47
Since neofetch is now contained in one file and Debian unstable package is updated really fast, i'm dropping support for Debian bintray repo. It will be available for some time yet, but will not receive updates.

**Comment by alexandergraul** [comment] 2018-08-02 20:55
Neofetch (5.0.0) is now in [openSUSE Tumbleweed](https://software.opensuse.org/package/neofetch).

**Comment by AngryPenguinPL** [comment] 2018-11-08 19:34
Neofetch 5.0.0 is available in x86, x86_64, znver1, aarch64 and ARMv7 for [OpenMandriva Cooker (upcoming Lx4)](https://abf.openmandriva.org/openmandriva/neofetch/build_lists/)

**Comment by lace22** [comment] 2018-11-26 20:05
the `http://dylanaraps.com/repo` repo doesn't work

**Comment by protonesso** [comment] 2019-01-08 16:33
neofetch is available in januslinux in "master" branch

**Comment by dylanaraps** [comment] 2019-01-08 16:35
Neofetch 6.0.0 has been released.

Sorry for the confusion with the 3 releases today. The first was a misclick while I was writing the changelog and the second is from a tag issue.

**Comment by dylanaraps** [comment] 2019-08-31 05:22
Neofetch 6.1.0 has been released.

**Closed** 2019-10-30 10:08 UTC
Labels: Discussion, Package
