### ISSUE TITLE
Images: Terminal size found as '0'

### ISSUE THREAD

**Issue by jingjinghack** [dylanaraps/neofetch#400] opened 2016-10-29 14:01 UTC
## Description

failed to use image.
## System Information

/usr/bin/neofetch: line 2085: width / font_width + gap + xoffset/font_width: division by 0 (error token is "font_width + gap + xoffset/font_width")
#### Neofetch version

1.9
#### Operating system

Ubuntu 16.04
## Screenshot

![2016-10-29 21-59-56](https://cloud.githubusercontent.com/assets/16219523/19830074/2156fa2e-9db6-11e6-9dfd-deaa26a94a90.png)
## Verbose log

https://gist.github.com/jingjinghack/c59810a269a2e0bc3bda3e230f56a749

**Comment by dylanaraps** [comment] 2016-10-30 03:15
`xdpyinfo` is for some reason reporting that your window size is `0` x `0` pixels. This is causing neofetch to fail when doing calculation related to your window size.

- What terminal emulator are you using?
- What does this command output?

`xwininfo -id "$(xdpyinfo | grep focus | grep -E -o 0x[0-9a-f]+)" | awk -F ': ' '/Width|Height/ {print $2 " "}'`

Note: I've pushed a change to master that will suppress the error and fallback to ascii mode.

**Comment by jingjinghack** [comment] 2016-10-30 04:28
@dylanaraps 
i'm using GNOME terminal.

xwininfo's output:

> zsh: no matches found: 0x[0-9a-f]+
> 655 
> 386

**Comment by dylanaraps** [comment] 2016-10-30 04:33
I can't reproduce this at all.

Does the issue still persist?

**Comment by jingjinghack** [comment] 2016-10-30 04:40
@dylanaraps 
There are problems, No display image.
![2016-10-30 12-37-39](https://cloud.githubusercontent.com/assets/16219523/19834528/0a6cb2ba-9e31-11e6-9094-99f3f5fd9f73.png)

**Comment by dylanaraps** [comment] 2016-10-30 04:42
Can you send me another verbose log?

**Comment by jingjinghack** [comment] 2016-10-30 04:47
@dylanaraps 
https://gist.github.com/jingjinghack/c9c2020ba9eeb179dec9a42579a11aea

**Comment by dylanaraps** [comment] 2016-10-31 03:55
Try the latest master, the issue should be fixed now.

**Comment by jingjinghack** [comment] 2016-11-01 05:33
@dylanaraps Thank you!  
![2016-11-01 13-32-19](https://cloud.githubusercontent.com/assets/16219523/19880377/c8dcda1e-9fca-11e6-9260-a20f40c7e088.png)

**Comment by dylanaraps** [comment] 2016-11-01 05:33
Anytime :)

**Closed** 2016-11-01 05:33 UTC
Labels: Bug, Can't Reproduce, images
