### ISSUE TITLE
Progress Bar Colors Not Reseting

### ISSUE THREAD

**Issue by jorgegonzalez** [dylanaraps/neofetch#661] opened 2017-02-23 17:22 UTC
## Description

The progress bar colors do not reset after the `bar_char_totals` are printed. The border character and the info that is printed at the end are the same color as `bar_color_total`.

## Screenshot

<img width="1280" alt="screen shot 2017-02-23 at 12 16 17 pm" src="https://cloud.githubusercontent.com/assets/12901172/23270519/108a2e10-f9c2-11e6-9c9d-96d6f9cd121a.png">

<img width="1280" alt="screen shot 2017-02-23 at 12 18 16 pm" src="https://cloud.githubusercontent.com/assets/12901172/23270559/2f26241e-f9c2-11e6-84f6-f35db2a41a58.png">

<img width="1280" alt="screen shot 2017-02-23 at 12 18 44 pm" src="https://cloud.githubusercontent.com/assets/12901172/23270579/3e215a2e-f9c2-11e6-9fa3-42aa9e40a25b.png">

<img width="1280" alt="screen shot 2017-02-23 at 12 20 57 pm" src="https://cloud.githubusercontent.com/assets/12901172/23270650/8d1f9a64-f9c2-11e6-9797-3fa45bcce08e.png">

## Config file

https://gist.github.com/jorgegonzalez/ba00cbefd8fe091aa8bd2a3152b224a4

## Edit

I have only seen this on MacOS. I don't know if Linux has this issue.

**Comment by dylanaraps** [comment] 2017-02-23 22:46
I can reproduce this.

**Comment by dylanaraps** [comment] 2017-02-23 23:20
I've half fixed the issue, still trying to figure out the rest of the problem.

The issue is fixed apart from the colors of the bar border. Those are still getting colored incorrectly for some reason. I'll keep this issue open till it's fully solved, just let me know if the info is colored correctly now.

**Comment by jorgegonzalez** [comment] 2017-02-24 14:01
No change on my end. Info is still getting colored like in the screenshots above.

**Comment by dylanaraps** [comment] 2017-02-25 08:03
The issue should be fixed now.

Please test it out and let me know.

**Closed** 2017-02-25 08:02 UTC
Labels: Bug

**Comment by jorgegonzalez** [comment] 2017-02-25 13:42
Yep it's all working. Thank you for fixing this.
