### ISSUE TITLE
Ability to read host differently

### ISSUE THREAD

**Issue by itz63c** [dylanaraps/neofetch#1427] opened 2020-03-14 17:16 UTC
## Description

Would it be possible for neofetch to identify host differently? 
Motherboard OEM's such as ASUS leave the system manufacturer / system product name fields blank and therefore no host is read to neofetch

dmidecode -s baseboard-product-name for example can still identify the motherboard's model, could this then be passed to the host label?

**Comment by dylanaraps** [comment] 2020-03-15 06:42
Output of: 

- `ls -l /sys/devices/virtual/dmi/id/*`
- `cat /sys/devices/virtual/dmi/id/*`

Also:

- `cat /sys/firmware/devicetree/base/model`

**Comment by itz63c** [comment] 2020-03-15 07:02
`ls -l /sys/devices/virtual/dmi/id/*
-r--r--r--. 1 root root 4096 Mar 15 03:00 /sys/devices/virtual/dmi/id/bios_date
-r--r--r--. 1 root root 4096 Mar 15 03:00 /sys/devices/virtual/dmi/id/bios_vendor
-r--r--r--. 1 root root 4096 Mar 15 03:00 /sys/devices/virtual/dmi/id/bios_version
-r--r--r--. 1 root root 4096 Mar 15 03:00 /sys/devices/virtual/dmi/id/board_asset_tag
-r--r--r--. 1 root root 4096 Mar 15 03:00 /sys/devices/virtual/dmi/id/board_name
-r--------. 1 root root 4096 Mar 15 03:00 /sys/devices/virtual/dmi/id/board_serial
-r--r--r--. 1 root root 4096 Mar 15 03:00 /sys/devices/virtual/dmi/id/board_vendor
-r--r--r--. 1 root root 4096 Mar 15 03:00 /sys/devices/virtual/dmi/id/board_version
-r--r--r--. 1 root root 4096 Mar 15 03:00 /sys/devices/virtual/dmi/id/chassis_asset_tag
-r--------. 1 root root 4096 Mar 15 03:00 /sys/devices/virtual/dmi/id/chassis_serial
-r--r--r--. 1 root root 4096 Mar 15 03:00 /sys/devices/virtual/dmi/id/chassis_type
-r--r--r--. 1 root root 4096 Mar 15 03:00 /sys/devices/virtual/dmi/id/chassis_vendor
-r--r--r--. 1 root root 4096 Mar 15 03:00 /sys/devices/virtual/dmi/id/chassis_version
-r--r--r--. 1 root root 4096 Mar 15 03:00 /sys/devices/virtual/dmi/id/modalias
-r--r--r--. 1 root root 4096 Mar 15 03:00 /sys/devices/virtual/dmi/id/product_family
-r--r--r--. 1 root root 4096 Mar 15 03:00 /sys/devices/virtual/dmi/id/product_name
-r--------. 1 root root 4096 Mar 15 03:00 /sys/devices/virtual/dmi/id/product_serial
-r--r--r--. 1 root root 4096 Mar 15 03:00 /sys/devices/virtual/dmi/id/product_sku
-r--------. 1 root root 4096 Mar 15 03:00 /sys/devices/virtual/dmi/id/product_uuid
-r--r--r--. 1 root root 4096 Mar 15 03:00 /sys/devices/virtual/dmi/id/product_version
lrwxrwxrwx. 1 root root    0 Mar 15 03:00 /sys/devices/virtual/dmi/id/subsystem -> ../../../../class/dmi
-r--r--r--. 1 root root 4096 Mar 15 03:00 /sys/devices/virtual/dmi/id/sys_vendor
-rw-r--r--. 1 root root 4096 Mar 15 03:00 /sys/devices/virtual/dmi/id/uevent

/sys/devices/virtual/dmi/id/power:
total 0
-rw-r--r--. 1 root root 4096 Mar 15 03:00 autosuspend_delay_ms
-rw-r--r--. 1 root root 4096 Mar 15 03:00 control
-r--r--r--. 1 root root 4096 Mar 15 03:00 runtime_active_time
-r--r--r--. 1 root root 4096 Mar 15 03:00 runtime_status
-r--r--r--. 1 root root 4096 Mar 15 03:00 runtime_suspended_time
`

`cat /sys/devices/virtual/dmi/id/*
07/29/2019
American Megatrends Inc.
5204
Default string
ROG STRIX B350-F GAMING
cat: /sys/devices/virtual/dmi/id/board_serial: Permission denied
ASUSTeK COMPUTER INC.
Rev X.0x
Default string
cat: /sys/devices/virtual/dmi/id/chassis_serial: Permission denied
3
Default string
Default string
dmi:bvnAmericanMegatrendsInc.:bvr5204:bd07/29/2019:svnSystemmanufacturer:pnSystemProductName:pvrSystemVersion:rvnASUSTeKCOMPUTERINC.:rnROGSTRIXB350-FGAMING:rvrRevX.0x:cvnDefaultstring:ct3:cvrDefaultstring:
cat: /sys/devices/virtual/dmi/id/power: Is a directory
To be filled by O.E.M.
System Product Name
cat: /sys/devices/virtual/dmi/id/product_serial: Permission denied
SKU
cat: /sys/devices/virtual/dmi/id/product_uuid: Permission denied
System Version
cat: /sys/devices/virtual/dmi/id/subsystem: Is a directory
System manufacturer
MODALIAS=dmi:bvnAmericanMegatrendsInc.:bvr5204:bd07/29/2019:svnSystemmanufacturer:pnSystemProductName:pvrSystemVersion:rvnASUSTeKCOMPUTERINC.:rnROGSTRIXB350-FGAMING:rvrRevX.0x:cvnDefaultstring:ct3:cvrDefaultstring:
`

`cat /sys/firmware/devicetree/base/model
cat: /sys/firmware/devicetree/base/model: No such file or directory
`

**Comment by dylanaraps** [comment] 2020-03-15 07:04
Is the information you'd like to display in the output you posted above?

**Comment by itz63c** [comment] 2020-03-15 07:07
yeah, ROG STRIX B350-F GAMING

**Comment by dylanaraps** [comment] 2020-03-15 07:11
Right. This is from `-r--r--r--. 1 root root 4096 Mar 15 03:00 /sys/devices/virtual/dmi/id/board_name`.

The problem is that this reads the motherboard name and the intention of this function's output is to identify the overall model of the system. Laptops show their model names, Virtual machines identify themselves, phones identify themselves, etc, etc.

Closing this as I believe that the motherboard name is not what we should be displaying here. You can simply add this to your neofetch config:

```
# inside print_info()
prin "host" "$(< /sys/devices/virtual/dmi/id/board_name)"
```

**Closed by dylanaraps** 2020-03-15 07:11 UTC
