### ISSUE TITLE
Extra newline with `--color_blocks on` when calling neofetch from `.bashrc` or `.bash_profile`.

### ISSUE THREAD

**Issue by lukelbd** [dylanaraps/neofetch#910] opened 2018-02-09 22:58 UTC
#### Description

[This thread](https://github.com/dylanaraps/neofetch/issues/628) suggests the extra newline with `neofetch --color_blocks off` is fixed. However this only seems to work when calling neofetch **directly**; when I call neofetch from a startup file (`.bashrc` or `.bash_profile`) there are still two extra newlines printed. Note this makes a total of three newlines with `--color_blocks off`, total of one newline with `--color_blocks on`. I have tried this in both `iTerm` and `Terminal`; the issue appears in both.

#### Neofetch version

Latest version: Neofetch 3.3.0

**Comment by dylanaraps** [comment] 2018-02-09 23:06
Does this still occur in the `-git` version?

**Comment by lukelbd** [comment] 2018-02-09 23:20
Using the current Github version, I get 4 newlines with `--color_blocks on` (empty, blocks, empty, empty) and 3 empty newlines with `--color_blocks off`. It does not change whether I call it from my `.bashrc` or call it directly.

But that's not exactly a fix; would prefer in both cases for there to be only one trailing newline.

**Comment by dylanaraps** [comment] 2018-02-10 21:53
Does the problem occur with the default config? `neofetch --config off`

I can't seem to reproduce this.

**Comment by lukelbd** [comment] 2018-02-14 23:16
Apparently I only get the issue when I startup a new terminal in iTerm2. If I re-source the `.bashrc`, I do not have the issue. I tried commenting out everything else in my `.bashrc` (in case something was interfering with `neofetch`) and the issue persists.

**Comment by SemperFu** [comment] 2018-05-16 20:46
I am currently running into this issue. If I use --color_blocks off in .bashrc it adds extra 3 newlines. I have also tried it with --config off and same issue. If I don't use --color_blocks it only adds 1 line. 

If I run the command command from the terminal it works fine.

**Comment by dylanaraps** [comment] 2018-05-23 22:07
Try the latest commit, I just pushed a fix.

**Comment by SemperFu** [comment] 2018-05-24 17:15
I just tried it, same problem. I want to do some more testing really quick with some other commands to make sure it actually is related to neofetch

**Comment by SemperFu** [comment] 2018-05-24 17:28
So it only seems to be when neofetch is ran first. It's first object adds 3 extra lines. The ones after it do not. 

I then put it in the middle with some cowsays first and it doesn't happen.

![neo1](https://user-images.githubusercontent.com/1786698/40501613-62252dec-5f56-11e8-8c4d-b77decd849a5.png)
![neo2](https://user-images.githubusercontent.com/1786698/40501616-64353550-5f56-11e8-9186-17db3eebeeae.png)

**Comment by dylanaraps** [comment] 2018-05-24 20:52
Try the latest commit :)

**Comment by SemperFu** [comment] 2018-05-25 00:55
This one errors out

> jasin@SiNNeR:~/Downloads$ ./neofetch
> ./neofetch: line 7: syntax error near unexpected token `newline'
> ./neofetch: line 7: `<!DOCTYPE html>'

**Closed** 2018-05-25 03:02 UTC
Labels: Bug
