### ISSUE TITLE
Empty infos on NixOS

### ISSUE THREAD

**Issue by Litarvan** [dylanaraps/neofetch#752] opened 2017-06-17 22:46 UTC
## Description

On my NixOS, running Neofetch displays the ASCII Art without any infos on the side

#### Neofetch version

Neofetch 3.0.1

## Screenshot

![Screenshot](https://image.noelshack.com/fichiers/2017/24/7/1497739583-nixpkgs-documents-nix-nixpkgs-nixpkgs-documents-nix-nixpkgs-nixos-modules-services-x11-display-managers-lightdm-greeters-web-nix-intellij-idea-2017-1-001.png)

## Config file

Not touched (just installed neofetch)

## Verbose log

https://gist.github.com/Litarvan/f3e8d0c81a3ddd7f5d33f0853c6b064d

**Comment by dylanaraps** [comment] 2017-06-18 06:43
How did you install Neofetch? It can't find it's default config.

**Comment by dylanaraps** [comment] 2017-06-18 07:34
The problem is that Neofetch can't find it's config file or a valid user config file. 

- Does `/etc/neofetch/config` exist?

**Comment by konimex** [comment] 2017-06-18 10:15
Neofetch 3.0.1 (and 3.1.0) released before commit https://github.com/dylanaraps/neofetch/commit/ece5ccf44b995843e4cd747352f09f4ae23b4a7c, which fixed the bug.

**Comment by konimex** [comment] 2017-06-20 21:54
Your config file is in `/usr/share/neofetch/config`, you can copy it to your `$HOME/.config/neofetch` directory.

This was a known issue and has been fixed in https://github.com/dylanaraps/neofetch/commit/d1fa88b7423cf8b9e4bc7445b9b6e37738b83869.

**Comment by dylanaraps** [comment] 2017-06-21 01:51
Update to the latest release and the issue should resolve itself.

**Comment by dawidd6** [comment] 2017-06-21 13:05
Adding this in > get_default_config is working

`  elif [[ -f "$HOME/.nix-profile/etc/neofetch/config" ]]; then
        default_config="$HOME/.nix-profile/etc/neofetch/config"`

**Comment by Litarvan** [comment] 2017-06-23 20:17
/etc/neofetch/config does not exist
There is no /usr on NixOS
And my ~/.config/neofetch folder is empty

And, i can't apply the fix of dawidd since the neofetch binary is read-only on NixOS

**Comment by dawidd6** [comment] 2017-06-23 20:28
Yes. One way is: you can fork neofetch and edit, then build nix package using official recipe from github
https://github.com/NixOS/nixpkgs/blob/df8195b6038136cfd08865be22e3e3c394990031/pkgs/tools/misc/neofetch/default.nix

or just copy neofetch somewhere else where you have write permission (/home for example), edit and run this copy.

**Comment by dylanaraps** [comment] 2017-06-23 22:49
I see what the issue is now,  my bad.

This will be fixed by https://github.com/dylanaraps/neofetch/pull/754 which removes the hard-coded paths from inside Neofetch.

**Comment by konimex** [comment] 2017-07-01 11:09
Closing this since #754 is merged.

**Closed by konimex** 2017-07-01 11:09 UTC
Labels: Bug
