### ISSUE TITLE
Neofetch can't seem to tell the difference between Antergos and Arch Linux

### ISSUE THREAD

**Issue by Risen-phoenix** [dylanaraps/neofetch#689] opened 2017-04-03 17:47 UTC
## Description

Neofetch says that I am running Arch Linux, despite the fact that I am running Antergos.

#### Neofetch version
3.0.2
## Screenshot
![screenshot at 2017-04-03 13-41-06](https://cloud.githubusercontent.com/assets/15039983/24622605/9dbafe5c-1873-11e7-93e0-360f51a45290.png)

## Config file
https://p.teknik.io/w0CKj
## Verbose log
https://p.teknik.io/ZZQbs

**Comment by mstraube** [comment] 2017-04-03 18:15
Have you installed the package` lsb-release`? If so try to remove it.
If I remember rightly that could be the problem because they use the package from the Arch repos.

**Comment by dylanaraps** [comment] 2017-04-03 22:44
This is a duplicate of https://github.com/dylanaraps/neofetch/issues/634.

**Closed by dylanaraps** 2017-04-03 22:44 UTC
