### ISSUE TITLE
ubuntu zesty

### ISSUE THREAD

**Issue by arnauldb** [dylanaraps/neofetch#439] opened 2016-11-13 21:00 UTC
## System Information
ubuntu zesty

"(self.id, self.codename))
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Ubuntu/zesty
"

**Comment by dylanaraps** [comment] 2016-11-13 21:04
Are you able to send me a log file and a screenshot?

1. Run `neofetch -vv 2> neofetchlog`
2. Upload the contents of `neofetchlog` to pastebin, gist or equivalent.

**Comment by dylanaraps** [comment] 2016-11-13 21:50
The error you're getting is a problem with your system based on the google search results I've found.

- http://askubuntu.com/questions/49040/apt-could-not-find-a-distribution-template-error
- http://ubuntu-bugs.narkive.com/koX73V3l/bug-1312673-re-software-properties-gtk-crashed-with-aptsources-distro-nodistrotemplateexception-in
- https://bugs.launchpad.net/ubuntu/+source/software-properties/+bug/1312673
- https://ubuntuforums.org/showthread.php?t=2276105

I'm pretty sure that you're seeing this error with neofetch because we're calling `apt-get` in the packages section. I'm marking this as not our bug until I can get a zesty VM up and running.

**Comment by dylanaraps** [comment] 2016-11-14 01:05
I created a Ubuntu Zesty VM and can't reproduce this. I'm going to close this issue as it's not a neofetch problem but a problem with your system.

**Closed by dylanaraps** 2016-11-14 01:05 UTC
Labels: Not Enough Info, Not our bug

**Comment by arnauldb** [comment] 2016-11-14 15:13
hello dylanaraps,

I just realized this, can't add any ppas anymore. Sorry to have bothered you with this and thanks for neofetch.

**Comment by dylanaraps** [comment] 2016-11-14 21:59
No problem :)
