### ISSUE TITLE
External IP used for local IP during an active OpenVPN connection

### ISSUE THREAD

**Issue by Tmplt** [dylanaraps/neofetch#220] opened 2016-04-07 17:49 UTC
**Distro**: Arch Linux (linux-zen kernel)

When I run `neofetch` with the option `info "Local IP" localip` during an active OpenVPN connection, my external IP provided by the VPN service is printed instead of my local IP. The issue does not remain if I disable the OpenVPN `.service`, but reappears if I enable it again.

**Comment by dylanaraps** [comment] 2016-04-10 23:09
Thanks for reporting this bug, I'm looking into other ways of getting the local IP so that this doesn't happen. I can't reproduce this myself so once I've come up with a fix I'd like you to test it out for me. :)

**Comment by dylanaraps** [comment] 2016-04-10 23:32
Does `hostname -i` print the correct local IP?

**Comment by Tmplt** [comment] 2016-04-11 13:27
```
$ hostname -i
127.0.0.1 127.0.0.1 
```
The output is the same even without the OpenVPN connection. I can, however, get the right IP with `ip addr show enp0s31f6`

**Comment by dylanaraps** [comment] 2016-04-12 03:37
Alright, it looks like we'll have to first find the current interface in use and then use a command like above to get the localip. I'll work on this when I get home tonight.

**Comment by dylanaraps** [comment] 2016-04-12 07:00
Does this print the correct local IP? I did some reading and this should work through VPN connections.

```sh
ip route get 8.8.8.8 | awk '{print $NF; exit}'
```

**Comment by Tmplt** [comment] 2016-04-12 12:50
It does not print the correct IP, no.

**Comment by dylanaraps** [comment] 2016-04-12 12:59
Is the correct IP listed in the output of this command?

```sh
ip addr | awk '/inet / {sub(/\/.*/, "", $2); print $2}'
```

**Comment by Tmplt** [comment] 2016-04-12 20:46
It is, yes:
```
$ ip addr | awk '/inet / {sub(/\/.*/, "", $2); print $2}'
127.0.0.1
192.168.0.11
[redacted; public IP]
```

**Comment by dylanaraps** [comment] 2016-04-13 05:50
How about this command?

```sh
ip -4 -o addr show dev $(ip route get 1 | awk '/dev/ {printf $5}') | awk '{split($4,a,"/");print a[1]}'
```

Sorry to make you keep testing commands, I don't have a vpn or openvpn setup.

**Comment by Tmplt** [comment] 2016-04-13 21:10
No worries.

That commands prints my external IP leased from the OpenVPN connection.

**Comment by dylanaraps** [comment] 2016-04-14 00:00
Here's what we need to do:

- Get the current network interface used for network connections.
- Get the local IP from said interface.

This is what `ip route get 1 | awk '{print $NF; exit}'` is supposed to do and it works extremely well except for when used with OpenVPN.

- Can you show me the output of `ip link` on your system with OpenVPN running?
- Can you show me the output of `ip link` on your system without OpenVPN running?

**Comment by Tmplt** [comment] 2016-04-14 13:35
With OpenVPN running:
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: enp0s31f6: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP mode DEFAULT group default qlen 1000
    link/ether 30:5a:3a:5a:1c:f1 brd ff:ff:ff:ff:ff:ff
3: tun0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 100
    link/none 
```
Without OpenVPN running:
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: enp0s31f6: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP mode DEFAULT group default qlen 1000
    link/ether 30:5a:3a:5a:1c:f1 brd ff:ff:ff:ff:ff:ff
```

**Comment by dylanaraps** [comment] 2016-04-14 13:58
Thanks, what about `ifconfig -a` with OpenVPN enabled/disabled?

**Comment by Tmplt** [comment] 2016-04-14 14:07
With OpenVPN running:
```
$ ifconfig -a
enp0s31f6: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.0.11  netmask 255.255.255.0  broadcast 192.168.0.255
        inet6 fe80::9fc:d6fd:ac7b:465c  prefixlen 64  scopeid 0x20<link>
        ether 30:5a:3a:5a:1c:f1  txqueuelen 1000  (Ethernet)
        RX packets 144738  bytes 183826186 (175.3 MiB)
        RX errors 0  dropped 133  overruns 0  frame 0
        TX packets 94611  bytes 25427707 (24.2 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 16  memory 0xdff00000-dff20000  

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1  (Local Loopback)
        RX packets 2625  bytes 1156992 (1.1 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 2625  bytes 1156992 (1.1 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

tun0: flags=4305<UP,POINTOPOINT,RUNNING,NOARP,MULTICAST>  mtu 1500
        inet [REDACTED; public IPv4]  netmask 255.255.255.224  destination 46.246.80.35
        inet6 [REDACTED; public IPv6]  prefixlen 64  scopeid 0x0<global>
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 100  (UNSPEC)
        RX packets 125402  bytes 153162642 (146.0 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 73504  bytes 10022414 (9.5 MiB)
        TX errors 0  dropped 2747 overruns 0  carrier 0  collisions 0
```
Without OpenVPN running:
```
$ ifconfig -a
enp0s31f6: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.0.11  netmask 255.255.255.0  broadcast 192.168.0.255
        inet6 fe80::9fc:d6fd:ac7b:465c  prefixlen 64  scopeid 0x20<link>
        ether 30:5a:3a:5a:1c:f1  txqueuelen 1000  (Ethernet)
        RX packets 145070  bytes 183893584 (175.3 MiB)
        RX errors 0  dropped 138  overruns 0  frame 0
        TX packets 94982  bytes 25634268 (24.4 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 16  memory 0xdff00000-dff20000  

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1  (Local Loopback)
        RX packets 2703  bytes 1202354 (1.1 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 2703  bytes 1202354 (1.1 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

**Comment by dylanaraps** [comment] 2016-04-29 01:13
I haven't been able to find a way to fix this sadly, does anyone have any ideas?

**Comment by iandrewt** [comment] 2016-05-01 05:57
I've just set up an OpenVPN server with DigitalOcean, and unless I'm reading this issue wrong, I cannot replicate this issue with Arch Linux (I switched today on my main PC). Local IP shows the address `10.8.0.6` (the one given out by the VPN), Public IP gives the public IP address of the DigitalOcean server.

`ip addr` gives the 127.0.0.1, my two local IPs, and the VPN IP (`10.8.0.6`) as expected with no mention of the server's public IP address

**Comment by Tmplt** [comment] 2016-05-01 11:10
Ah. I'm sorry for the confusion.

I too get the IP given out by the VPN if I'm connected through it. I thought it would output the regular `192.168.X.X` instead, but perhaps my issue is the expected behaviour?

**Comment by dylanaraps** [comment] 2016-05-02 23:18
I think your output is the expected behavior, thanks for testing this out @iandrewt. 

I think we should close this now.

**Closed** 2016-05-03 23:16 UTC
Labels: Bug, Help Wanted
