### ISSUE TITLE
is it possible to make neofetch compatible with lolcat?

### ISSUE THREAD

**Issue by Neil-seu** [dylanaraps/neofetch#914] opened 2018-02-14 16:03 UTC
![archmerge_2018-02-14_16-01-52](https://user-images.githubusercontent.com/24956423/36214093-73b9001e-11a0-11e8-871a-d5a36edef229.png)

**Comment by Rizwan-Hasan** [comment] 2018-02-14 19:23
Need this

**Comment by dylanaraps** [comment] 2018-02-14 20:48
No

Duplicate of #666, #685, #747. 

Check for previous issues before op ning another one.

**Closed by dylanaraps** 2018-02-14 20:48 UTC

**Comment by konimex** [comment] 2018-02-15 00:03
It is *kind of* possible with `--stdout`, but no ASCII art.

**Comment by dylanaraps** [comment] 2018-06-19 22:55
Neofetch now works with `lolcat`! :fireworks:

**Comment by Neil-seu** [comment] 2018-06-24 14:09
Yeah I saw that and tested it!! Thank you so much!! And sorry for the late
reply!😣

**Comment by ProxyNeko** [comment] 2018-12-05 03:18
I know this was said to be fixed but I'm still getting the issue even after downloading version 5 from the releases here on Github. had it installed from Debian repos at first until I found out that is no longer updated so just swapped the files over and still the same issue. Any pointers?

**Comment by ARAGATO** [comment] 2019-03-07 05:53
Same here. Just tried it with neofetch v6.0.0 and output is still buggy.

**Comment by treier57lol** [comment] 2019-05-19 09:51
I got it working, the problem was that I installed lolcat with apt, which installed an old version, 42.0.99. I removed lolcat, installed it with `gem install lolcat` and rebooted. Everything now works!

**Comment by kaanoguzhan** [comment] 2020-09-12 22:04
> Neofetch now works with `lolcat`! 🎆

An Explanation could be nice you know

**Comment by G3NSVRV** [comment] 2021-09-13 18:25
it is possible to only print the ascii art in lolcat colouring and the rest as default?
