### ISSUE TITLE
Image not displaying

### ISSUE THREAD

**Issue by cdhoffmann** [dylanaraps/neofetch#845] opened 2017-10-17 02:06 UTC
## Description

I have attempted to display an image via the following methods: 
* neofetch --iterm2
* neofetch --iterm2 /path/to/img
* neofetch --iterm2 /path/to/dir/
No matter what, i end up with the following thumbnail displayed:

#### Neofetch version
3.0.3

## Screenshot
<img width="711" alt="screen shot 2017-10-16 at 7 49 03 pm" src="https://user-images.githubusercontent.com/10753118/31642961-1e0ada06-b2ab-11e7-8cb1-0cd731257cdc.png">

## Config file
[config.txt](https://github.com/dylanaraps/neofetch/files/1389502/config.txt)

## Verbose log

https://pastebin.com/r9UAsJtL

**Comment by dylanaraps** [comment] 2017-10-17 03:18
The log file is from Neofetch run in `ascii` mode, can you upload a log file of `iterm2` mode?

**Comment by cdhoffmann** [comment] 2017-10-17 04:25
@dylanaraps Sorry about that. Here is the updated log: https://pastebin.com/r9UAsJtL

**Comment by kelaun** [comment] 2017-10-17 09:06
Hi, 
It is the same as the issue I logged yesterday as well.
In my log it seemed like it could not find the image in the path I gave it, but after checking it the path and image are in the location passed to neofetch (see screenshots).
<img width="575" alt="bug1" src="https://user-images.githubusercontent.com/11407575/31656210-3cdbbace-b32b-11e7-9682-240cdc3b4236.png">
<img width="568" alt="bug2" src="https://user-images.githubusercontent.com/11407575/31656211-3cf039ae-b32b-11e7-93a7-013d96aed367.png">

**Comment by dylanaraps** [comment] 2017-10-19 03:51
Duplicate of #844.

**Closed by dylanaraps** 2017-10-19 03:51 UTC
