### ISSUE TITLE
Add Überzug image support

### ISSUE THREAD

**Issue by dawidpotocki** [dylanaraps/neofetch#1172] opened 2019-01-18 12:05 UTC
[Überzug](https://github.com/seebye/ueberzug) is command line Python3 util which allows to draw images on terminals. In my experience it is more reliable than w3m and works in pretty much any terminal (tested on st, termite, urxvt, kitty, alacritty, gnome-terminal, konsole, lxterminal, xterm).

This is example of simple displaying image using Überzug in bash:

```
source "`ueberzug library`"

# process substitution example:
ImageLayer 0< <(
    ImageLayer::add [identifier]="example0" [x]="0" [y]="0" [path]="/path/to/image.png"
    read
    ImageLayer::remove [identifier]="example0"
    read
)
```

So I guess it wouldn't be that hard to implement it?

**Comment by dylanaraps** [comment] 2019-01-18 16:12
I don't like the idea of sourcing the library. Also it looks like it requires `bash 4` due to the associative arrays. Is there not a way of just doing `ueberzug img.jpg`?

**Comment by dawidpotocki** [comment] 2019-01-19 02:32
Oh yes, there is. I nearly gave up on searching for it. I loved seeing these useless messages:

```
Usage:
    ueberzug ROUTINE [options]
```

Sooo helpful... but whatever, so there is one quick dirty example:

```shell
#!/usr/bin/env bash

function ImageLayer {
    ueberzug layer -sp json
}

# ~/ doesn't work
path_to_image="/home/dawidpotocki/.config/wallpaper"
x_padding=0
y_padding=0

function add_image {
	echo "{\"action\": \"add\", \"identifier\": \"image\", \"x\": $x_padding, \"y\": $y_padding, \"path\": \"$path_to_image\"}";
}

ImageLayer -< <(
	add_image
	# there is some way to make image show even after command completes, as it works when sourcing library, but I'm not sure how
	sleep 1000
)

```

There is probably some way to make it more clean, but I'm just too stupid for that :P.

**Comment by ShayBox** [comment] 2019-01-24 17:48
Would be great to support a backend that works on all terminals unlike literally every other backend

**Comment by ShayBox** [comment] 2019-01-25 02:02
I'm unaware of that backend, I tried all the ones listed on the GitHub repo wiki, ascii and caca work but they're ascii, w3m will flicker showing the image but won't stay, my terminal is st.

On January 24, 2019, at 6:31 PM, Hans Petter Jansson <notifications@github.com> wrote:

@ShayBox Sorry to butt in here, but -- does Chafa fail on your terminal? It really shouldn't.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.￼

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/dylanaraps/neofetch","title":"dylanaraps/neofetch","subtitle":"GitHub repository","main_image_url":"<a href="https://github.githubassets.com/images/email/message_cards/header.png">https://github.githubassets.com/images/email/message_cards/header.png</a>","avatar_image_url":"<a href="https://github.githubassets.com/images/email/message_cards/avatar.png">https://github.githubassets.com/images/email/message_cards/avatar.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/dylanaraps/neofetch">https://github.com/dylanaraps/neofetch</a>"}},"updates":{"snippets":[{"icon":"PERSON","message":"@hpjansson in #1172: @ShayBox Sorry to butt in here, but -- does Chafa fail on your terminal? It really shouldn't."}],"action":{"name":"View Issue","url":"<a href="https://github.com/dylanaraps/neofetch/issues/1172#issuecomment-457398326">https://github.com/dylanaraps/neofetch/issues/1172#issuecomment-457398326</a>"}}} [ { "@context": "<a href="http://schema.org">http://schema.org</a>", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "<a href="https://github.com/dylanaraps/neofetch/issues/1172#issuecomment-457398326">https://github.com/dylanaraps/neofetch/issues/1172#issuecomment-457398326</a>", "url": "<a href="https://github.com/dylanaraps/neofetch/issues/1172#issuecomment-457398326">https://github.com/dylanaraps/neofetch/issues/1172#issuecomment-457398326</a>", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "<a href="https://github.com">https://github.com</a>" } } ]

**Comment by dawidpotocki** [comment] 2019-01-25 03:13
From what I see [Chafa is showing images in "ascii"](https://fedoramagazine.org/wp-content/uploads/2018/07/sir.gif), so it isn't really good solution.

**Comment by hpjansson** [comment] 2019-01-25 14:58
Chafa shows the image in the terminal using terminal characters. w3m and Überzug open a new X11 window on top of the terminal. The flickering in w3m is probably caused by changes in window stacking or some other bug.

That's beside the point, though -- @ShayBox said every backend fails, and I was curious if that included Chafa. If so, they should probably open a separate bug for that as Chafa is designed to work with every terminal, over ssh, etc.

**Comment by seebye** [comment] 2019-01-25 21:54
> w3m and Überzug open a new X11 window on top of the terminal. 
That's wrong w3m draws on the terminal window, that's why everything disappears on a redraw.  
Ueberzug creates a child window within the terminal window and handles e.g. X11 exposure events.

**Comment by SearyBlue** [comment] 2019-04-04 16:25
a

**Comment by RaitaroH** [comment] 2019-04-30 09:12
Thanks to @seebye and @dawidpotocki I got this to work. I will provide a patch (as a txt file cus github). There are 2 issues (though not a big deal, nor I think even possible to fix due to the nature of uberzug itself)
+ you cannot type while uberzug is running
+ if you scroll then the image moves with your scroll
[uberzug.txt](https://github.com/dylanaraps/neofetch/files/3130573/uberzug.txt)

**Comment by dawidpotocki** [comment] 2019-04-30 09:59
> you cannot type while uberzug is running
You mean having picture with your shell prompt? Because you actually can
type when script is running.

> if you scroll then the image moves with your scroll
I think that would not be an issue and actually a good thing. Though it
doesn't happen for me in st and other terminal emulators.

**Comment by RaitaroH** [comment] 2019-04-30 10:12
@dawidpotocki Well I suppose that having uberzug run in the background instead would be better and fix issue 1. Tho I am not so sure where to do that.

**Comment by seebye** [comment] 2019-04-30 11:00
Ueberzug should be used as daemon and it aims more to be used in tuis than in cli programs.  
It doesn't work as w3m which just draws on the terminal emulators window.  
(It creates it's own child window and handles exposure, ... events)  
So images will disappear on the death of the process.  

@dylanaraps So that's why there's no command like `ueberzug img.jpg`.  
It's also possible to build commands like this.  
Also there's no need to use the library.  
```bash
function join_by { local IFS="$1"; shift; echo "$*"; }
function ueberzug_show {
    join_by $'\t' action "add" identifier "image" x "$1" y "$2" path "$3"
}

{ ueberzug_show 0 0 "/some/path/some-image.jpg"; read; } | ueberzug layer --parser simple &>/dev/null
```

> if you scroll then the image moves with your scroll
@RaitaroH Create a new screen -> fixed

**Comment by RaitaroH** [comment] 2019-04-30 12:03
Much more elegant. Thank you @seebye

**Comment by dylanaraps** [comment] 2019-04-30 13:03
I will look into this. :+1:

**Comment by GaugeK** [comment] 2019-07-02 07:37
Any updates?

**Comment by dylanaraps** [comment] 2019-08-27 13:57
I have no interest in this feature whatsoever, however I will accept a pull request adding this functionality to `neofetch`. 

No one other than myself has actually attempted to add support for this backend or asked for my help in doing so. 

The main issue I have with Uberzug is the lack of it being able to be run as a one-off command. It needs to run as a daemon and I'm not sure if this model will fit the way images are handled in Neofetch.

I'm open to pull requests and willing to help someone get this merged.

**Comment by dylanaraps** [comment] 2020-01-22 22:49
As no one seems to want to implement this, discussion can now take place here: https://github.com/dylanaraps/neofetch/issues/1392

**Closed by dylanaraps** 2020-01-22 22:49 UTC
Labels: Enhancement
