### ISSUE TITLE
[Ubuntu Server] Linuxbrew: Neofetch doesn't install correctly.

### ISSUE THREAD

**Issue by LoganDark** [dylanaraps/neofetch#671] opened 2017-03-02 20:04 UTC
## Description

If you're suggesting a new feature then just a description will suffice.

#### Neofetch version
unknown

## Screenshot
it doesn't output anything, not even one newline

## Config file
unchanged

## Verbose log

1. Run `neofetch -vv 2> neofetchlog`
2. Upload the contents of `neofetchlog` to pastebin, gist or equivalent.

`neofetch -vv 2` always prints to the console, no matter what redirection method I try to use.

```
+ verbose=on
+ shift
+ [[ -n 2 ]]
+ case "$1" in
+ shift
+ [[ -n '' ]]
+ get_distro
+ get_bold
+ case "$ascii_bold" in
+ case "$bold" in
+ get_distro_colors
+ case "$ascii_distro" in
+ set_colors 1 7 3
++ color 1
++ case "$1" in
++ printf %b '\033[0m\033[31m'
+ c1=''
++ color 7
++ case "$1" in
++ printf %b '\033[0m'
+ c2=''
++ color 3
++ case "$1" in
++ printf %b '\033[0m\033[33m'
+ c3=''
++ color ''
++ case "$1" in
++ printf %b '\033[38;5;m'
+ c4=''
++ color ''
++ case "$1" in
++ printf %b '\033[38;5;m'
+ c5=''
++ color ''
++ case "$1" in
++ printf %b '\033[38;5;m'
+ c6=''
+ [[ '' != \o\f\f ]]
+ set_text_colors 1 7 3
+ [[ '' == \d\i\s\t\r\o ]]
++ color ''
++ case "$1" in
++ printf %b '\033[38;5;m'
+ title_color=''
++ color ''
++ case "$1" in
++ printf %b '\033[38;5;m'
+ at_color=''
++ color ''
++ case "$1" in
++ printf %b '\033[38;5;m'
+ underline_color=''
++ color ''
++ case "$1" in
++ printf %b '\033[38;5;m'
+ subtitle_color=''
++ color ''
++ case "$1" in
++ printf %b '\033[38;5;m'
+ colon_color=''
++ color ''
++ case "$1" in
++ printf %b '\033[38;5;m'
+ info_color=''
+ [[ '' == \d\i\s\t\r\o ]]
++ color ''
++ case "$1" in
++ printf %b '\033[38;5;m'
+ bar_color_elapsed=''
+ case "$bar_color_total $1" in
++ color ''
++ case "$1" in
++ printf %b '\033[38;5;m'
+ bar_color_total=''
+ ascii_file=ubuntu
+ [[ '' != \d\i\s\t\r\o ]]
+ color_text=off
+ set_colors
++ color ''
++ case "$1" in
++ printf %b '\033[38;5;m'
+ c1=''
++ color ''
++ case "$1" in
++ printf %b '\033[38;5;m'
+ c2=''
++ color ''
++ case "$1" in
++ printf %b '\033[38;5;m'
+ c3=''
++ color ''
++ case "$1" in
++ printf %b '\033[38;5;m'
+ c4=''
++ color ''
++ case "$1" in
++ printf %b '\033[38;5;m'
+ c5=''
++ color ''
++ case "$1" in
++ printf %b '\033[38;5;m'
+ c6=''
+ [[ off != \o\f\f ]]
+ [[ xterm-256color != \m\i\n\i\x ]]
+ trap 'printf "\033[?25h\033[?7h"' EXIT
+ printf '\033[?25l\033[?7l'
+ image_backend
+ [[ ! '' =~ ^(off|ascii)$ ]]
+ type -p convert
+ case "${image_backend:-off}" in
+ image_backend=off
+ [[ off != \o\f\f ]]
+ old_functions
+ type printinfo
+ get_cache_dir
+ case "$os" in
+ cache_dir=/tmp
+ print_info
+ dynamic_prompt
+ case "$image_backend" in
+ return
+ [[ off == *w3m* ]]
+ [[ '' == \o\n ]]
+ [[ on == \o\n ]]
+ printf %b '[!]\033[0m Config: Default config not found, continuing...\n[!]\033[0m Config: Sourced user config.    (/h'
[!] Config: Default config not found, continuing...
[!] Config: Sourced user config.    (/home/logandark/.config/neofetch/config)
+ return 0
+ printf '\033[?25h\033[?7h'
```

**Comment by konimex** [comment] 2017-03-03 07:45
No default config found. That's weird.

**Comment by dylanaraps** [comment] 2017-03-08 21:44
How have you installed neofetch?

**Comment by LoganDark** [comment] 2017-03-08 23:23
homebrew

**Comment by dylanaraps** [comment] 2017-03-09 00:15
What are the outputs of these commands?: 

```sh
whereis neofetch
ls /usr/local/etc/neofetch
ls /usr/local/share/neofetch
```

**Comment by LoganDark** [comment] 2017-03-09 00:17
the issue has since been fixed, so those commands will not be accurate.

i installed neofetch from source with `make`, which seemed to work

the issue might be that brew doesn't (and won't let you) run as root access

**Comment by dylanaraps** [comment] 2017-03-09 00:20
Weird.

Can anyone else on a macOS machine reproduce this using the homebew package?

**Comment by LoganDark** [comment] 2017-03-09 00:22
Sorry I didn't state the OS.

**Comment by LoganDark** [comment] 2017-03-09 00:23
I was using Ubuntu Server 16.10. Since I have neofetch now, let me drop a screenshot.

![Neofetch](https://puu.sh/uAqP4/6a7b53f8e3.png)

**Comment by dylanaraps** [comment] 2017-03-09 00:23
I'm not sure that neofetch works with linuxbrew in the first place.

I'll install linuxbrew and see if I can reproduce this.

**Comment by LoganDark** [comment] 2017-03-09 00:24
Also, another note, linuxbrew was installed with `sudo apt-get install linuxbrew-wrapper` and then installed using `brew` without root.

**Comment by LoganDark** [comment] 2017-03-09 00:26
Please remove the incorrect `Mac OS` label

**Comment by dylanaraps** [comment] 2017-03-09 04:25
I can't seem to get linuxbrew working on both of my machines so I'll ask you this:

How does linuxbrew handle installing the files that are supposed to go into `/usr/local/etc` and `/usr/local/share`?

**Comment by LoganDark** [comment] 2017-03-09 06:53
Idk tbh

**Comment by dylanaraps** [comment] 2017-03-09 07:03
I'm going to close this as a `wontfix` as we don't officially support linuxbrew and I'm 100% sure that the reason for the original error is neofetch's files being installed to non-standard directories.

**Closed by dylanaraps** 2017-03-09 07:03 UTC
Labels: Not Enough Info
