### ISSUE TITLE
Image only shows a split-second if run a second time

### ISSUE THREAD

**Issue by Trollwut** [dylanaraps/neofetch#507] opened 2016-12-06 11:39 UTC
## Description

The first command `neofetch` runs it as intended, showing an image.

On the next running, it display the image for a split second, but then disappears - the remaining neofetch is displayed correctly. But without a picture.

[I've recorded a video showing the running of some neofetch a few times.](https://github.com/dylanaraps/neofetch/files/633700/neofetch_issue.mkv.zip)

#### Neofetch version

neofetch 2.0.1-1

## Screenshot

[Screenshot with spec](http://i.imgur.com/iXVYhnX.png) (runs with compton, if that matters)

## Verbose log

[neofetchlog.txt](https://github.com/dylanaraps/neofetch/files/633716/neotechlog.txt)

**Comment by dylanaraps** [comment] 2016-12-06 12:16
What terminal emulator are you using? I'm trying to reproduce this.

**Comment by Trollwut** [comment] 2016-12-06 13:12
Oh me idiot, forgot the important part. :D

It's on `xfce4-terminal` and on the sidebar-terminal (which is the same).

**Comment by dylanaraps** [comment] 2016-12-06 13:59
I can't reproduce this at all, can you upload your config file? There might be some image related options causing this.

**Comment by Trollwut** [comment] 2016-12-06 17:49
[You just want to ripoff my beautiful progress bars!](https://github.com/dylanaraps/neofetch/files/634594/config.txt)

Sure mate, there you go. :)

**Comment by dylanaraps** [comment] 2016-12-06 23:40
I still can't reproduce this using `xfce4-terminal`, `Fire Mono` and your config file. The image displays perfectly every-time. 

Here's a video:

[neofetch-test.zip](https://github.com/dylanaraps/neofetch/files/635316/neofetch-test.zip)

**Comment by Trollwut** [comment] 2016-12-07 10:17
Shouldn't be compton, because when I `killall compton`, the problem still exists.

Maybe this helps: If I start two Terminals and run `neofetch` on one, the image displays fine (as always on first run). But when I click on the other terminal, the image disappears.

(Doesn't have to be another terminal. It's just when the neofetch one loses focus.)

**Comment by dylanaraps** [comment] 2016-12-07 10:33
This is a known issue with `w3m-img` and certain terminals, you'll notice that the images also disappear if they get covered by another window or you change workspaces. This issue affects all programs using w3m-img to display images. `w3m`, `ranger` and etc. 

Unless Neofetch is run inside of a loop (so it draws the images continuously) there's nothing we can do to fix this. Example: `while :; do neofetch; sleep 1; done`

Now about the original issue: Unless I or someone else can figure out how to reliably reproduce this issue there's no way we can fix it.

I'll keep this issue open in the hopes that someone else is affected and I'll also keep investigating to see if I can find a cause.

**Comment by Trollwut** [comment] 2016-12-07 11:11
Ah ok, because in a normal terminal, the image stays until the terminal loses focus. The dropdown terminal displays the image just for a split-second, so I guess it's more a dropdown-terminal issue?

Well ok, maybe someone will have the same issue, I'll stick with ascii til then. :)

**Comment by Trollwut** [comment] 2017-01-02 13:15
Never used these softwares. Should there be a preview in the right side of the terminal? If so, it doesn't work with ranger. :) http://i.imgur.com/E22VbyF.png

Otherwise you can give me a sample command with ranger or w3m to test.

**Comment by dylanaraps** [comment] 2017-01-02 22:59
This wiki page will help you get ranger running with `w3m-img`.

https://github.com/ranger/ranger/wiki/Image-Previews

For `w3m` just running `w3m "https://github.com/dylanaraps/neofetch"` should show all of the README images.

**Comment by Trollwut** [comment] 2017-01-03 00:51
Yes, images (while using your w3m command).

If I use "Page Up" and "Page Down" keys to navigate, no images show. But while scrolling with the arrow keys, I get them.

**Comment by dylanaraps** [comment] 2017-01-03 01:02
This might be because `w3m` and `ranger` redraw the images constantly, neofetch only draws them twice and exits. I'll add an option to constantly redraw the images and we'll see if it works.

**Comment by Trollwut** [comment] 2017-01-03 01:22
Sure mate, keep me up to date. :)

**Comment by dylanaraps** [comment] 2017-01-03 01:47
Can you test out #587?

Just launch neofetch with `--loop` and let me know if it fixes the issue. :)

**Comment by dylanaraps** [comment] 2017-01-04 22:56
Ping @Trollwut

**Comment by dylanaraps** [comment] 2017-01-11 22:09
Ping @Trollwut

**Comment by Trollwut** [comment] 2017-01-14 02:21
Hey sorry, haven't been at home this week. :)

Ok, I'm not used to how Github works, may you please elaborate on what I should do?

BTW before departure, I tested around a bit. EVERY terminal worked fine with it, except the xfce4-terminal in drop-down mode. I'm pretty sure it's because the drop-down mode will draw it a second time, resulting in losing the image.

**Comment by dylanaraps** [comment] 2017-01-14 02:52
All good!

Here's how you can test the new branch:

1. `git clone https://github.com/dylanaraps/neofetch`
2. `cd neofetch`
3. `git checkout loop`
4. `./neofetch --loop`
    - Example: `neofetch --image /path/to/img.jpg --loop`
5. `Ctrl+C` to exit neofetch.

I'll try out drop down mode in XFCE.

**Comment by Trollwut** [comment] 2017-01-14 15:31
Had to test it on second PC, as I don't have XFCE/dropdown anymore on main. My second PC had the disappearing on about every third encounter of neofetch. Now it works fine.

`-v` of --loop is as follow:

    [!] Config: Sourced default config. (/usr/share/neofetch/config)
    [!] Config: Sourced user config.    (/home/trollwut/.config/neofetch/config)
    [!] Config: speed_type='bios' is deprecated, use speed_type='bios_limit' instead.
    [!] Config: ascii_logo_size is deprecated, use ascii_distro='{arch,crux,gentoo}_small' instead.
    [!] Config: $start and $end are deprecated, use block_range=(0 7) instead.

**Comment by Trollwut** [comment] 2017-01-14 15:33
I think that sometimes the dropdown redraws, sometimes not. I guess it has to do something when using it together with e.g. `compton`.

If I don't use compton on second computer, the image always stays. With compton, sometimes it disappeares.

But as I said... I don't use it anymore anyways on the main machine, so... for me the problem would be closed. Dunno if it is helpful for further development.

**Comment by dylanaraps** [comment] 2017-01-14 21:17
I'll close this issue, it seems like it's an issue with w3m-img and certain configurations. Thanks for being patient with this issue. :)

**Closed by dylanaraps** 2017-01-14 21:17 UTC
Labels: Bug, Can't Reproduce
