### ISSUE TITLE
Incorrect info displayed on MacBook6,2 macOS Sierra

### ISSUE THREAD

**Issue by jchonig** [dylanaraps/neofetch#453] opened 2016-11-25 02:04 UTC
## Description

Incorrect info on macOS Sierra

1. Hz is missing for the monitor
2. Total memory is displayed wrong

#### Neofetch version
Git:
b96b1e4c59efee35ef4c51aee60ab626bbbaf14

#### Operating system

macOS sierra

## Screenshot
 jch@jch-air.home.honig.net 
-------------------------- 
OS: macOS Sierra 10.12.1 16B2555 x86_64 
Model: MacBookAir6,2 
Kernel: 16.1.0 
: 6 days, 6 hours, 50 minutes 
Packages: 684 
Shell: bash 3.2.57 
Resolution: 1440x900 @ Hz 
DE: Aqua 
WM: Quartz Compositor 
Terminal: Apple_Terminal 
CPU: Intel i5-4250U (4) @ 1.30GHz 
GPU: Intel HD Graphics 5000 
Memory: 4170MB / 8388610MB  

## Verbose log
[neofetch.txt](https://github.com/dylanaraps/neofetch/files/612362/neofetch.txt)

**Comment by dylanaraps** [comment] 2016-11-25 02:10
@iandrewt, can you take a look at this?

**Comment by dylanaraps** [comment] 2016-11-25 02:19
**Resolution:**

What's the output of these commands?
- `screenresolution get`
- `screenresolution get | awk '/Display/ {printf $6 "Hz, "}'`
- `system_profiler SPDisplaysDataType | awk '/Resolution:/' `
- `system_profiler SPDisplaysDataType | awk '/Resolution:/ {printf $2"x"$4" @ "$6"Hz, "}'`

**Memory:**

What's the output of these commands?

- `sysctl -n hw.memsize`
- `echo "$(($(sysctl -n hw.memsize) / 1024^2))"`

**Comment by dylanaraps** [comment] 2016-11-25 02:22
Notes:

- If we divide your incorrect total memory number (8388610) by `1024` again, it gives us `8192`. This is the correct amount. We may need to add a separate case for Sierra systems(?).

**Comment by jchonig** [comment] 2016-11-25 02:31
**jch@jch-air[628]:~$** screenresolution get
-bash: screenresolution: command not found
**jch@jch-air[629]:~$** system_profiler SPDisplaysDataType | awk '/Resolution:/'
          Resolution: 1440 x 900
**jch@jch-air[630]:~$** system_profiler SPDisplaysDataType | awk '/Resolution:/ {printf $2"x"$4" @ "$6"Hz, "}'
1440x900 @ Hz, 
**jch@jch-air[631]:~$** sysctl -n hw.memsize
8589934592
**jch@jch-air[632]:~$** echo "$(($(sysctl -n hw.memsize) / 1024^2))"
8388610

I think your Notes are a good summary except for the Sierra part.  I have an old iMac running El Capitan (I can't update it to Sierra it's too old) and see similar results there:

**jch@jch-air[635]:~$** celie system_profiler SPDisplaysDataType | awk '/Resolution:/'
          Resolution: 1920 x 1200

**jch@jch-air[637]:~$** celie sysctl -n hw.memsize
6442450944

Thanks.

Jeff

**Comment by dylanaraps** [comment] 2016-11-25 02:36
Thanks for that!

I'm certain now that the resolution bug is caused by `system_profiler` sometimes not printing the refresh rate. I'll add a check to see if the refresh rate exists before appending `Hz` to the output.

Does this command display the right memory total?

`echo "$(($(sysctl -n hw.memsize) / 1024 / 1024))"`

**Comment by jchonig** [comment] 2016-11-25 03:00
**jch@jch-air[641]:~$** echo "$(($(sysctl -n hw.memsize) / 1024 / 1024))"
8192

Thanks for the quick fix!

**Comment by dylanaraps** [comment] 2016-11-25 03:03
Does this PR fix the refresh rate issue? https://github.com/dylanaraps/neofetch/pull/454

**Comment by jchonig** [comment] 2016-11-25 03:19
Yes:

*Resolution*: 1440x900

Thanks

Jeff

-- 
Jeffrey C. Honig <jch@honig.net>
https://jchonig.withknown.com
GnuPG ID:14E29E13 <http://jch.honig.net/Home/pgp_key>
Keybase: jchonig <https://keybase.io/jchonig>

**Comment by dylanaraps** [comment] 2016-11-25 03:22
Both fixes have been merged into master, thanks for testing!

**Closed by dylanaraps** 2016-11-25 03:22 UTC
Labels: Bug

**Comment by jchonig** [comment] 2016-11-25 03:35
Looks good now!


Thanks

Jeff

-- 
Jeffrey C. Honig <jch@honig.net>
https://jchonig.withknown.com
GnuPG ID:14E29E13 <http://jch.honig.net/Home/pgp_key>
Keybase: jchonig <https://keybase.io/jchonig>
